### PR TITLE
style: update sql runner sidebar UI

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/3735

### Description:

with dbt cloud
CleanShot 2022-11-15 at 17 49 32@2x

without dbt cloud
CleanShot 2022-11-15 at 17 49 25@2x

removed a lot of inconsistencies and style redundancies between pages. here's a video 

https://user-images.githubusercontent.com/962095/201963385-3057f928-5202-4fdd-a4a1-f41b9d0cf406.mp4

Right now sidebar component is not shared between pages but we'll be dealing with that soon once we start working on the content/layout redesign milestone

cc: @PriPatel

### CODE REVIEW

**Review by ZeRego — COMMENTED** [review]
Sidebar resize is only available in the saved chart  page. Could we keep it for the tables and explore page and add it to the sql runner sidebar ?

**Comment by IrakliJani** [comment]
@ZeRego good point! I was tempted to do it in the same PR but I feel like its out of the scope. 

as mentioned above:
> Right now sidebar component is not shared between pages but we'll be dealing with that soon once we start working on the content/layout redesign milestone

now that I think about it more, I think it will be better to create a separate issue to remove sidebar discrepancies between pages before the redesign

**Comment by ZeRego** [comment]
> now that I think about it more, I think it will be better to create a separate issue to remove sidebar discrepancies between pages before the redesign
> thoughts?

Yes, I think we should create a separate ticket. But just to be clear this PR is removing functionality temporarily from some sidebars, even though they are still using the `useSidebarResize` hook. And we plan to move this resize logic to the generic sidebar component so it can be used on any page.

**Comment by IrakliJani** [comment]
that should not have happened. I'll fix it now

**Comment by IrakliJani** [comment]
@ZeRego fixed

**Review by ZeRego — APPROVED** [review]
lgtm 👍

**Pull request merged**
