### PR TITLE
feat: Error messages changed

### PR DESCRIPTION
**Pull request by Inder782**
Closes: #9956

### Description:
Changed the error messages.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by magnew — APPROVED** [review]
Looks good. Ran e2e locally.

**Comment by magnew** [comment]
@all-contributors add @Inder782 for code

**Review by magnew — CHANGES_REQUESTED** [review]
Actually I see an issue.

**Comment by magnew** [comment]
> Actually I see an issue.

The failing test crashes locally. I didn't notice it failing on a local run. It shouldn't be failing based on what's in this review, but I haven't figured out why.

**Comment by magnew** [comment]
> > Actually I see an issue.
> 
> The failing test crashes locally. I didn't notice it failing on a local run. It shouldn't be failing based on what's in this review, but I haven't figured out why.

Ok, this failing test is failing everywhere. It's not this review. I'm going to merge this.

**Review by magnew — APPROVED** [review]

**Comment by Inder782** [comment]
Thanks @magnew feels good getting started, will look more issues where I can contribute

**Comment by magnew** [comment]
> Thanks @magnew feels good getting started, will look more issues where I can contribute

Excellent. I'm not sure what the stack of good contributor issues looks like right now, but let us know if you don't find something.

**Pull request merged**
