### PR TITLE
feat: improve chart from dashboard edit ux

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: #6752

### Description:

When editing a chart from a dashboard: 
* See `Save changes`
* See `Cancel changes` **only** when there are unsaved changes
* Add go-back (Icon arrow back) button that goes back only, displays a prompt if the user has unsaved changes, before going back to the og dashboard. 
* Display tooltip on hover of new go-back button

Screen recording: 

https://github.com/lightdash/lightdash/assets/7611706/5c30fc41-29c5-4438-b6c2-e4d7f57cd20d

### CODE REVIEW

**Comment by hamzahc1** [comment]
@joaoviana - this works well but the copy `Go Back` doesn't seem right 🤔. Can we use a symbol for `Return` instead? I wouldn't use the same icon we use for "cancel changes" or undo like from dashboard filters but maybe just a backwards arrow with a tooltip on hover that says "Return to dashboard"?

**Comment by joaoviana** [comment]
> @joaoviana - this works well but the copy `Go Back` doesn't seem right 🤔. Can we use a symbol for `Return` instead? I wouldn't use the same icon we use for "cancel changes" or undo like from dashboard filters but maybe just a backwards arrow with a tooltip on hover that says "Return to dashboard"? 

That sounds great @hamzahc1, the icon + tooltip approach shall be done ✔️ 
Yea thinking about it now, "go back" is quite vague and not that appropriate for this context

**Comment by joaoviana** [comment]
@hamzahc1 added new icon + tooltip: 

https://github.com/lightdash/lightdash/assets/7611706/a8963ad0-37f0-4e1c-a68a-f016672f7f3f

I think it looks ok on the left of the 3-dot button, but could also be the first button, like this: 
image

**Review by hamzahc1 — APPROVED** [review]
Works great!

**Review by magnew — APPROVED** [review]
Looks good!

**Pull request merged**
