### PR TITLE
feat(#261): sql runner

### PR DESCRIPTION
**Pull request by ZeRego**
Closes: #261 

Note: I already have some tickets for [SQL runner v2](https://github.com/lightdash/lightdash/milestone/22)

Preview:
<a href="https://www.loom.com/share/9e3d41827ab84893932aea88aa109609">
    <p>Lightdash - sql runner preview - Watch Video</p>
    
  </a>

### CODE REVIEW

**Review by owlas — CHANGES_REQUESTED** [review]
Looks awesome! Two UX things:

* The shortcuts overlay is opened using `?`. It might be more obvious to provide a button too to show shortcuts. The BigQuery UI has a very obvious one
Screenshot 2021-11-08 at 12 33 19

* Could we make the alert message about "we detected these tables" less obvious. I was thinking some secondary (light grey) text at the bottom saying "tables missing?" and a tooltip explaining that we only pull models from dbt.

**Comment by ZeRego** [comment]
> Looks awesome! Two UX things:
> 
> * The shortcuts overlay is opened using `?`. It might be more obvious to provide a button too to show shortcuts. The BigQuery UI has a very obvious one
> 
> Screenshot 2021-11-08 at 12 33 19

Since we are going to have hotkeys/shortcuts in multiple pages, it would be nice to have that button in the same place in all the pages. I was also imagining us having a glossary so people can learn some of our terms.  

Screenshot 2021-11-08 at 13 49 05

I thought about the footer but is going to become overcrowded. I would propose us changing the help button from redirecting to the documents page to open a help modal. This modal would have a glossary, page shortcuts, contact information and a button to docs. What you think ? @owlas @TuringLovesDeathMetal 

> * Could we make the alert message about "we detected these tables" less obvious. I was thinking some secondary (light grey) text at the bottom saying "tables missing?" and a tooltip explaining that we only pull models from dbt.

We can make it grey and change the message a bit. What you think ? This message would be removed once we display the warehouse tables (#758)
Screenshot 2021-11-08 at 13 31 11

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego When you query a table with a bunch of results, if the table is too large, you have no option to scroll left/right. It also hides the side bar and removes the `run query` buttons in the top 🤔 

https://lightdash-pr-729.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner

image

**Comment by TuringLovesDeathMetal** [comment]
^here's the query I ran:
```
SELECT *
     FROM "jaffle_db_pr_729"."jaffle"."customers" LEFT JOIN "jaffle_db_pr_729"."jaffle"."orders" ON orders.customer_id = customers.customer_id
```

**Comment by ZeRego** [comment]
> https://lightdash-pr-729.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner

@TuringLovesDeathMetal Good find. This is a general bug for the app since it also happens in the explore page. We should open a separate issue for this. Side bar should have a min/fixed width and the results table should have a horizontal scroll when needed.

Screenshot 2021-11-08 at 14 22 01

**Comment by owlas** [comment]
> I thought about the footer but is going to become overcrowded. I would propose us changing the help button from redirecting to the documents page to open a help modal. This modal would have a glossary, page shortcuts, contact information and a button to docs. What you think ? @owlas @TuringLovesDeathMetal

If "shortcuts" was behind the help button it would still not be clear that shortcuts are available. 

I guess the main one here is cmd+enter? Maybe we can just put that in small writing under the text input or even on the button e.g. "Hit cmd+enter to run query"

**Comment by owlas** [comment]
> We can make it grey and change the message a bit. What you think ? This message would be removed once we display the warehouse tables

If it's temporary I don't mind

**Comment by TuringLovesDeathMetal** [comment]
>  I would propose us changing the help button from redirecting to the documents page to open a help modal. This modal would have a glossary, page shortcuts, contact information and a button to docs. What you think ?

^Love this idea!

Where is this shortcuts thing everyone is talking about btw? I can't find it 🤔 

> I was thinking some secondary (light grey) text at the bottom saying "tables missing?" and a tooltip explaining that we only pull models from dbt.

^ I prefer this call to action/ context - it's what people are thinking when they're looking for this message. The message of "we only pull dbt models" is the _**why**_ but it's not so much the _**what**_, and I feel like the what is more important in getting across in these warning messages/contextual messages.

**Comment by ZeRego** [comment]
> Where is this shortcuts thing everyone is talking about btw? I can't find it 🤔

@TuringLovesDeathMetal You can see it in the [preview video](https://www.loom.com/share/9e3d41827ab84893932aea88aa109609). I ran the query by hitting `cmd + enter` instead of pressing the button. And if you press `shift + ?` it opens a modal with all the available shortcuts.

**Comment by TuringLovesDeathMetal** [comment]
> I guess the main one here is cmd+enter? Maybe we can just put that in small writing under the text input or even on the button e.g. "Hit cmd+enter to run query"


^A lot of these shortcuts are normally there when you hover over something (e.g. if you hover over the run query button, it will say `command + enter`)

I can't imagine us having so many shortcuts that we'd need a list for them...but I could be wrong!

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal @owlas How does this look like ? 

<a href="https://www.loom.com/share/68ed5a4f2d074068bfb2740667dc2fff">
    
  </a>

**Pull request merged**
