### PR TITLE
feat: add additionalmetrics to runquery

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1757

### Description:
Add additionalMetrics to runQuery

### Preview:
Getting query

Screenshot from 2022-04-13 10-59-18

Saving query
Screenshot from 2022-04-13 11-00-02

### Scope of the changes (select all that apply):
- [x] Frontend  
- [x] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
@owlas did I miss something ? it is a bit hard to test everything because it is not currently used

**Comment by owlas** [comment]
QA'd via the API:

- [x] Can run query
- [ ] Can save query

```
###
# @name runQueryWithAdditionalMetrics
POST {{baseUrl}}/projects/3675b69e-8324-4110-bdca-059031aa8da3/explores/customers/runQuery
Content-Type: application/json

{
  "dimensions": [
    "customers_first_name"
  ],
  "metrics": [
    "customers_unique_customer_count",
    "customers_mymetric"
  ],
  "sorts": [
    {
      "fieldId": "customers_unique_customer_count",
      "descending": true
    }
  ],
  "filters": {},
  "limit": 500,
  "tableCalculations": [],
  "additionalMetrics": [
    {
      "name": "mymetric",
      "label": "my metric",
      "type": "count",
      "fieldType": "metric",
      "table": "customers",
      "tableLabel": "customers",
      "sql": "${TABLE}.customer_id",
      "compiledSql": "COUNT(customers.customer_id",
      "isAutoGenerated": false,
      "hidden": false
    }
  ]
}
```

**Comment by owlas** [comment]
@rephus if I save a chart I don't get back the full metric definition in `additionalMetrics` - do you know why this is?

**Request**

```
POST {{baseUrl}}/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved
Content-Type: application/json

{
  "tableName": "customers",
  "metricQuery": {
    "dimensions": [
      "customers_first_name"
    ],
    "metrics": [
      "customers_unique_customer_count",
      "customers_mymetric"
    ],
    "filters": [],
    "sorts": [
      {
        "fieldId": "customers_unique_customer_count",
        "descending": true
      }
    ],
    "limit": 500,
    "tableCalculations": [],
    "additionalMetrics": [
      {
        "name": "mymetric",
        "label": "my metric",
        "type": "count",
        "fieldType": "metric",
        "table": "customers",
        "tableLabel": "customers",
        "sql": "${TABLE}.customer_id",
        "compiledSql": "COUNT(customers.customer_id",
        "isAutoGenerated": false,
        "hidden": false
      }
    ]
  },
  "chartConfig": {
    "type": "cartesian",
    "config": {
      "layout": {
        "xField": "customers_first_name",
        "yField": [
          "customers_mymetric"
        ]
      },
      "eChartsConfig": {
        "series": [
          {
            "encode": {
              "xRef": {
                "field": "customers_first_name"
              },
              "yRef": {
                "field": "customers_mymetric"
              }
            },
            "type": "bar"
          }
        ]
      }
    }
  },
  "tableConfig": {
    "columnOrder": [
      "customers_unique_customer_count",
      "customers_mymetric",
      "customers_first_name"
    ]
  },
  "name": "aaaaa"
}
```

**Response**
```
{
  "status": "ok",
  "results": {
    "uuid": "fb70fba3-369f-451d-ab16-85839cde5486",
    "projectUuid": "3675b69e-8324-4110-bdca-059031aa8da3",
    "name": "aaaaa",
    "tableName": "customers",
    "updatedAt": "2022-04-14T11:20:13.253Z",
    "metricQuery": {
      "dimensions": [
        "customers_first_name"
      ],
      "metrics": [
        "customers_unique_customer_count",
        "customers_mymetric"
      ],
      "filters": [],
      "sorts": [
        {
          "fieldId": "customers_unique_customer_count",
          "descending": true
        }
      ],
      "limit": 500,
      "tableCalculations": [],
      "additionalMetrics": [
        {
          "field_type": "metric",
          "type": "count",
          "is_auto_generated": false
        }
      ]
    },
    "chartConfig": {
      "type": "cartesian",
      "config": {
        "layout": {
          "xField": "customers_first_name",
          "yField": [
            "customers_mymetric"
          ]
        },
        "eChartsConfig": {
          "series": [
            {
              "type": "bar",
              "encode": {
                "xRef": {
                  "field": "customers_first_name"
                },
                "yRef": {
                  "field": "customers_mymetric"
                }
              }
            }
          ]
        }
      }
    },
    "tableConfig": {
      "columnOrder": [
        "customers_unique_customer_count",
        "customers_mymetric",
        "customers_first_name"
      ]
    }
  }
}
```

**Review by owlas — CHANGES_REQUESTED** [review]
see comment above

**Comment by rephus** [comment]
> @rephus if I save a chart I don't get back the full metric definition in `additionalMetrics` - do you know why this is?

That's probably because our Metric model in DB doesn't contain all those parameters, 

https://github.com/lightdash/lightdash/pull/1764/files#diff-61514ec33a87b0e81904845b39993bcdee5f254fd217d648a07266074f82aa14
image

My bad, I didn't include all the fields from the extension `Field` , just the one in metrics ... I'll fix it

**Comment by rephus** [comment]
image

https://github.com/lightdash/lightdash/pull/1764/commits/4b28ae0b40daab26eef1e662d4bf48e77fa0ade6 

@owlas should this fix the issue ?

**Pull request merged**
