### PR TITLE
fix: fix incorrect chart_type in database and dashboard

### PR DESCRIPTION
**Pull request by karan0handa**
Closes: #6810 

### Description:

The database reads both 'How many orders did we get on February' and 'Which customers have not recently ordered an item' as `vertical_bar` even though they're `table`. Psql screenshot ->

psql

This happens because in [02_saved_queries.ts](https://github.com/lightdash/lightdash/blob/main/packages/backend/src/database/seeds/development/02_saved_queries.ts) both the incorrect charts have `chartConfig.config === undefined`. 

In `createSavedChart` in [SavedChartModel.ts](https://github.com/lightdash/lightdash/blob/main/packages/backend/src/models/SavedChartModel.ts), `last_version_chart_kind` defaults to `ChartType.TABLE` because `getChartKind()` returns `undefined`.

This PR fixes it. I also cross-checked by making the chartConfig.config in [02_saved_queries.ts](https://github.com/lightdash/lightdash/blob/main/packages/backend/src/database/seeds/development/02_saved_queries.ts) defined with dummy values.

Let me know if this works :)

I haven't been able to run tests because my docker seems to crash every time I try. Hopefully the Github actions will take care of it.

fix

### Reviewer actions

- [x] I have manually tested the changes in the preview environment
- [x] I have reviewed the code
- [x] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by rephus — APPROVED** [review]
Great investigation ! yeah you are correct about the config being undefined on 02_saved_queries . This should not cause any backward compatibility issues. 

I am running tests on render, if everything seems fine, I'll merge it. 

Thanks.

**Comment by rephus** [comment]
@all-contributors add @karan0handa for code

**Comment by rephus** [comment]
image
Formatting failed on test, could you update it , if not I can do it on my branch

`yarn workspace @lightdash/common format -w` should work

**Comment by karan0handa** [comment]
Sure, I'll update it manually.

**Comment by karan0handa** [comment]
@rephus Done!

**Pull request merged**
