### PR TITLE
feat: grouping dimensions and metrics

### PR DESCRIPTION
**Pull request by ZeRego**
Closes: #1851 

### Description:

Changes:
- added support for groupLabel in the dimension/metric/dbt metric yml
- moved table tree component next to the explore tree component
- render group in sidebar
- allow node click to expand group ( currently only expands on click the arrow icon )

Screenshot 2022-07-12 at 13 31 41

groups

yml example:
```
      - name: created
        meta:
          dimension:
            groupLabel: Dates
          metrics:
            date_of_most_recent_created_customer:
              type: max
              group_label: Dates
```

### CODE REVIEW

**Comment by hamzahc1** [comment]
Does this also let you search by the group name in the sidebar?

**Comment by Martin-Carlsson** [comment]
Does this only allow for one level of grouping?

Could we allow for something like this:
```
     - name: created
        meta:
          dimension:
            groupLabel: Sales/Customers/Dates
          metrics:
            date_of_most_recent_created_customer:
              type: max
              group_label: Sales/Customers/Dates
```

**Comment by Martin-Carlsson** [comment]
Are we able to order groups?

**Comment by ZeRego** [comment]
> Does this also let you search by the group name in the sidebar?

@hamzahc1 Current implementation only searches dimensions and metrics. How would the search work in that case (both groups and dimensions/metrics? Would it show the group empty if the search matches the group label but doesn't match any of the dimensions inside ?

> Does this only allow for one level of grouping?

@Martin-Carlsson Currently yes, this ticket is to provide the basic functionality and after getting feedback, like yours, we will keep improve it.
Note that the sidebar already has a deep hierarchy with 5 levels, `Table -> dimensions/metrics group -> custom group -> dimension/metric -> date interval dimension` so perhaps we need to rethink this structure if we want to support nested grouping labels. 🤔  I created a new ticket for it #2686

> Are we able to order groups?

@Martin-Carlsson Right now it is possible to force the order by prefixing the label with numbers or white spaces.
Eg:
`group_label: 'Third'` 
`group_label: ' Second'` // has 1 white space so its second
`group_label: '  First'` // has 2 white spaces so it is first

If we want to have configuration for the group labels we might need to add it in the model meta.
```
models:
  - name: customers
    meta:
      group_labels:
          - name: Test
            order: 1
          - name: "Another Test"
            order: 2
```

**Review by rephus — APPROVED** [review]
Code looks great, let me test this locally

**Comment by rephus** [comment]
If you select a dimension within a group, you can't collapse the group, is that intentional ? 
Peek 2022-07-13 08-58

**Comment by rephus** [comment]
Works like a charm :ok_hand: 
image

**Comment by ZeRego** [comment]
Closing this ticket as it provides the simplest version of grouping. 
We have a separate ticket in our backlog to change the sidebar UI/UX #2685. Feel free to add suggestions in that ticket 😃

**Pull request merged**
