### PR TITLE
feat: verify email on email update

### PR DESCRIPTION
**Pull request by yasmin-e**
Closes: #3726 

### Description:
https://user-images.githubusercontent.com/67699259/223789911-b4b918bb-cae4-4c69-b9e0-31cd09561d1a.mov

### CODE REVIEW

**Comment by ZeRego** [comment]
We should hide the Email verification UI if the server doesn't have an email server configured. 
We can check that in the FE with
```
const { health } = useApp();
health.data?.hasEmailClient // boolean
```

**Review by TuringLovesDeathMetal — CHANGES_REQUESTED** [review]
Nice! this looks great :) 

Can we just remove the helper text from the bottom of this modal? It doesn't really make sense in verifying emails, but important in onboarding

image

**Comment by ZeRego** [comment]
Every time I clicked 'verify' I would have to wait 2 seconds for the UI to show me an error or success. 
Would be nice for the button to show loading state and the form disabled while is waiting for the BE.

**Review by TuringLovesDeathMetal — APPROVED** [review]
Nice! Updates look great :) so quick on this one, and it's awesome! well done ❤️

**Pull request merged**
