### PR TITLE
chore: upgrade github workflows

### PR DESCRIPTION
**Pull request by la55u**
Related: https://github.com/lightdash/lightdash/issues/9028

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by ZeRego** [comment]
@la55u are you still working on this or is it ready to review? 👀

**Comment by la55u** [comment]
> @la55u are you still working on this or is it ready to review? 👀

I think I'll hand it over to someone with more experience in GitHub actions to finish. I believe the changes so far are correct (ready to merge) the only missing workflow is the docker build one which has the artifacts upload/download action that has a breaking change - because of the matrix - which I didn't have time to investigate yet. 
All other actions are mostly just a bump from node 16->20 which shouldn't cause any problem since other parts of the development environment is already using that.

**Comment by la55u** [comment]
@ZeRego Update: I've now upgraded the Docker build workflow too and I believe it concludes the work for this PR. Let me know it it needs anything else.
I've used [this guide](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners) as a reference to update the artifact handling actions.

**Comment by rephus** [comment]
Everything seems to work (some e2e tests are failing, but they are unrelated). Thanks for your contribution

**Review by rephus — APPROVED** [review]

**Pull request merged**
