### PR TITLE
feat: Migrate Project settings > dbt Cloud to use Mantine 

### PR DESCRIPTION
**Pull request by jayanand05**
Closes: #5406

### Description:
Updated Project settings > dbt Cloud to use Mantine

https://github.com/lightdash/lightdash/assets/113882904/f32c0849-b3b9-40ae-9424-b238cec48624

### CODE REVIEW

**Comment by IrakliJani** [comment]
hey @jayanand05 can you rebase this branch? I see a lot of unrelated commits in this PR. thanks!

**Comment by jayanand05** [comment]
hi @IrakliJani , give me some time i am having issue while doing rebase.

**Comment by IrakliJani** [comment]
no worries @jayanand05, let me know if you need help!

**Comment by jayanand05** [comment]
hi @IrakliJani , i think i doing something wrong can you guide me on the steps i need to take for rebase?

**Comment by IrakliJani** [comment]
sure thing @jayanand05 

- First, delete your main branch if it is corrupted and does not contain work that needs to be saved.
- Pull down a fresh main branch from the original Lightdash repository, not your forked version.
- Switch to your feature branch (feat-migrate-to-mantine).
- Do a git rebase -i main to interactively rebase onto the new main branch.
- In the editor that opens, you can drop unrelated commits by replacing "pick" with "drop" in front of the commit messages.
- Specifically, drop all commits except the "migrate to mantine" commit.
- Save and exit the editor when done.

This will rebase your feature branch onto the new main, excluding unrelated commits.

let me know if that works for you!

**Comment by jayanand05** [comment]
i did all those steps

**Comment by jayanand05** [comment]
22 files got changed 🤯

**Comment by IrakliJani** [comment]
hmm, does not look right. I'll clean it up for you later today

**Comment by jayanand05** [comment]
can't we go without rebase?

**Comment by jayanand05** [comment]
Got it I am getting into to fix it!

**Comment by jayanand05** [comment]
looks good now, Thanks a lot @IrakliJani for helping out.

**Comment by IrakliJani** [comment]
@jayanand05 thanks for rebasing the PR. I added some fixes to the pr:

- fixed layout and removed hardcoded PX values
- fixed clear button
- fixed form hooks with inputs
- added valudations

waiting e2e before merging. thanks for your contribution 🙌

**Review by IrakliJani — APPROVED** [review]

**Pull request merged**
