### PR TITLE
feat: invite user with specific role

### PR DESCRIPTION
**Pull request by ZeRego**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #2209 

### Preview:

Screenshot 2022-05-26 at 13 28 30

### Scope of the changes (select all that apply):
- [x] Frontend  
- [x] Backend  
- [x] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
On error, the form resets Peek 2022-05-26 15-49

**Comment by rephus** [comment]
I was trying to break /login after the invite is created, but before the user is activated. The frontend doesn't allow login without passwords, and we don't have password reset... can you think about any other edgecase ? Maybe if the user logins via google ?

**Review by rephus — APPROVED** [review]
Code looks good, and it works as expected. I'm just not sure why we had to change the whole invitation /user creation, instead of adding `role` to the invitation model... This could cause additional changes on our metrics, just by adding an invitation it could impact directly the `number of users per org`

**Comment by TuringLovesDeathMetal** [comment]
> Can you remind me what we decided about tracking ?

When a new user is created for an invite, we trigger an `invite_created` event **_not_** a `user_created` event. 

When a user accepts the invitation (i.e. when they first login), we trigger a `user_created`/`identifies` event.

**Comment by ZeRego** [comment]
> > Can you remind me what we decided about tracking ?
> 
> When a new user is created for an invite, we trigger an `invite_created` event **_not_** a `user_created` event.
> 
> When a user accepts the invitation (i.e. when they first login), we trigger a `user_created`/`identifies` event.

Thanks! Cool, so I don't need to change anything :)

**Pull request merged**
