### PR TITLE
fix: Disables total toggle for line/area/scatter charts, only show for bar charts.

### PR DESCRIPTION
**Pull request by rohitverma007**
Closes: #7408 

### Description:
Showing the total toggle only for BAR charts.

### Reviewer actions

- [x] I have manually tested the changes in the preview environment
- [x] I have reviewed the code
- [x] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by rephus** [comment]
Your only commit doesn't follow our naming convention `Only show total for bar charts` , that's why one of the tests fails. 

To fix this, you can push another commit with any name so we can squash them and use the title instead (you can use ---allow-empty)

**Comment by rephus** [comment]
Also there is a problem with the file formatting, did you disable the pre-commit hook ? 

> [warn] src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx

you can run it manually by doing 

> yarn workspace frontend format -w

**Comment by rephus** [comment]
I tested this and works as expected. Thanks

We just need to fix the failing tests.

**Comment by rohitverma007** [comment]
thanks for the help @rephus, updated!

**Review by rephus — APPROVED** [review]

**Comment by rephus** [comment]
@all-contributors add @rohitverma007 for code

**Pull request merged**
