### PR TITLE
fix: always run query before validating diffs

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: N/A

### Description:

- Always runs query before getting validation
- Skips validation & column diffing if the user has already accepted/reviewing the changes that will happen if they edit the virtual view

recording:

https://github.com/user-attachments/assets/f6bc9dfd-a37e-48c8-876e-27139198d9f1

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by rephus** [comment]
Could you deploy this on render ?

**Comment by joaoviana** [comment]
there should be a render environment now @rephus , if you found the PR ok, feel free to merge 😄

**Review by rephus — APPROVED** [review]
Tested

**Comment by rephus** [comment]
Unrelated E2E errors

**Pull request merged**
