### PR TITLE
feat: add updated user on charts and dashboards

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #465

### Description:
Add updatedAt on dashboards and charts 

### Preview:

image

image

Screenshot from 2022-04-14 08-57-05

### Scope of the changes (select all that apply):
- [x] Frontend  
- [x] Backend  
- [x] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
Approved design 
image

**Comment by rephus** [comment]
TODO fix tests

**Comment by hamzahc1** [comment]
@rephus I tried QA'ing this but ran into a couple of things: 

1. After making a change in the saved chart, the "save" button remains clickable 
2. After saving a dashboard or chart and going back to the main menu - you have to wait for a while before the list updates saying "updated a few seconds ago" 

I recorded a Loom of the experience: https://www.loom.com/share/da1753dbba4443ddb6f315b6bb397137

**Comment by hamzahc1** [comment]
The above mentioned might be out of scope for this PR though so I can open a new issue for them!

**Review by owlas — APPROVED** [review]

**Pull request merged**
