### PR TITLE
fix: adjust chart totals based on legends selected

### PR DESCRIPTION
**Pull request by CVamsi27**
Closes: #5081 

### Description:
Adjust chart totals based on legends selected

### Screen Shots:
https://github.com/lightdash/lightdash/assets/55316723/407d9b13-fe30-481e-a822-a11c1628812b

### CODE REVIEW

**Comment by CVamsi27** [comment]
Hello @rephus, create a new PR as #5894 was closed last week and I was not able to re - open. Implemented the changes suggested here, everything is working as expected
Thanks

**Comment by rephus** [comment]
Some unit tests are failing, could you fix them ? 
image

**Comment by rephus** [comment]
> Hello @rephus, unit tests are passing now.

:+1:  thanks, I'll deploy these changes to render to test them

**Comment by CVamsi27** [comment]
> > Hello @rephus, unit tests are passing now.
> 
> 👍 thanks, I'll deploy these changes to render to test them

Sure @rephus, please let me know if there is anything else.

**Comment by CVamsi27** [comment]
Hello @rephus, I found the reason of the failure (fix - made parameter optional) and fixed it

**Comment by rephus** [comment]
I've tested this locally, it is working as expected. 

Note: disabled legends do not persist when the chart is saved , I guess this is ok and it was not initially covered on the ticket. If needed, we can make a separate ticket for that. @TuringLovesDeathMetal

**Comment by rephus** [comment]
Oh no... I found a bug.. If you toggle the legend checkbox, then it breaks , although the total is calculated correcly. It seems a bit of an edge case, should we merge it as it is @TuringLovesDeathMetal  ? 

[Screencast from 03-07-23 16:02:27.webm](https://github.com/lightdash/lightdash/assets/1983672/c509d14b-3746-460f-ab96-8a0fe37391ea)

e2e test pass, so I'm happy to merge otherwise.

**Comment by CVamsi27** [comment]
@rephus, When toggled, totals seem off. Looking into it.

**Comment by rephus** [comment]
I think it is ok as it is, it seems a bit hard to fix without breaking anything else. I can create a new ticket for it just to keep the record

**Comment by CVamsi27** [comment]
@rephus, Sorry for the bug, working on it, will fix and raise a new PR asap.

**Pull request merged**
