### PR TITLE
feat: project list in create preview modal

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/12170

### Description:
CleanShot 2024-11-04 at 23 39 25@2x

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
@IrakliJani in the project list, the selected project is greyed out (to appear selected): 
image


What happens if I don't have access to a project? Is it also greyed out? (if yes, it feels like this might be a bit confusing?)
image

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal nice catch, fixed! 😎

**Comment by TuringLovesDeathMetal** [comment]
loooks great !!! 😍

**Comment by hamzahc1** [comment]
@andrewdw are you still able to review this?

**Review by magnew — APPROVED** [review]
Code looks good, works great

**Pull request merged**
