### PR TITLE
chore: reuse combine filters

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/7246

### Description:

extracts filter combinators to common/filter/utils and reuses them in fe/be

### CODE REVIEW

**Review by magnew — CHANGES_REQUESTED** [review]
I don't obviously see what's causing this in the code, but I think this change keeps the all dashboard charts from loading. I checked render and locally and I see this:

Kapture 2023-09-28 at 19 19 05

Looks like that's why the tests are failing too, so yay tests! 😄

**Comment by IrakliJani** [comment]
> I don't obviously see what's causing this in the code, but I think this change keeps the all dashboard charts from loading. I checked render and locally and I see this: 
> Looks like that's why the tests are failing too, so yay tests! 😄

looks like my change was missing a useMemo so it was re-rendering + refetching infinitely 😂

**Comment by magnew** [comment]
> > I don't obviously see what's causing this in the code, but I think this change keeps the all dashboard charts from loading. I checked render and locally and I see this:
> > Looks like that's why the tests are failing too, so yay tests! 😄
> 
> looks like my change was missing a useMemo so it was re-rendering + refetching infinitely 😂

That's how to keep the data up to date :D

**Review by magnew — APPROVED** [review]
Looks good!

**Pull request merged**
