### PR TITLE
feat: dimension color chart

### PR DESCRIPTION
**Pull request by rephus**
Closes:  #4458

### Description:

Screenshot from 2024-04-22 15-35-00

Screenshot from 2024-04-22 15-34-44

Screenshot from 2024-04-22 16-15-04

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by TuringLovesDeathMetal — APPROVED** [review]
This looks great! Could we please update the docs with the changes 🤞

**Comment by rephus** [comment]
This requires docs, it can be done  on a separate ticket

**Review by almeidabbm — APPROVED** [review]
Also works great with `additional_dimensions` 🎉 :

image

image

Checked all acceptance criteria in the ticket and there's just one that I am not sure:

- "If a group is using one of the colours from the default palette, then that colour is not reused by another group in the same chart. For example, in this chart, if I'd assigned garden of sweden to the same green colour as plant paradise, then garden of sweden would be green, and plant paradise would be assigned the next "available" colour in my default colour palette." 

https://github.com/lightdash/lightdash/assets/22939015/056cf717-5cc6-4c61-ade1-ce257d341af8

**Comment by rephus** [comment]
>     "If a group is using one of the colours from the default palette, then that colour is not reused by another group in the same chart. For example, in this chart, if I'd assigned garden of sweden to the same green colour as plant paradise, then garden of sweden would be green, and plant paradise would be assigned the next "available" colour in my default colour palette."

Yeah... not sure about that. We can investigate if this becomes an issue.. what do you think ?

**Comment by rephus** [comment]
> Also works great with additional_dimensions 🎉 :

That was not intentional :sweat_smile: but good to know

**Comment by almeidabbm** [comment]
> > ```
> > "If a group is using one of the colours from the default palette, then that colour is not reused by another group in the same chart. For example, in this chart, if I'd assigned garden of sweden to the same green colour as plant paradise, then garden of sweden would be green, and plant paradise would be assigned the next "available" colour in my default colour palette."
> > ```
> 
> Yeah... not sure about that. We can investigate if this becomes an issue.. what do you think ?

yep yep, I agree, also I was setting the color manually to one in the palette so not really sure what will be the decision regarding that 👌 LGTM

**Comment by rephus** [comment]
Docs https://deploy-preview-9847--peaceful-bassi-cbf284.netlify.app/references/dimensions#colors

**Pull request merged**
