### PR TITLE
feat: spaces - resource list actions

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/2915

**Dashboard section**
- [x] `Create new dashboard` should create a new dashboard in the current space and redirect the user to the blank dashboard. 
- [x] `Add existing dashboard` should open the existing modal
- [x] Remove the '`Create new dashboard`' button from the modal

**Chart sections**
- [x] 'Create new chart' should create a new explore in the current space and redirect the user to the blank explore. 
- [x] `Add existing chart` should open the existing modal
- [x] Remove the `Create new chart` button from the modal

https://user-images.githubusercontent.com/962095/189861852-24b96337-326a-48f6-b073-31c6cfde8284.mp4

### CODE REVIEW

**Comment by IrakliJani** [comment]
@PriPatel can you stamp your approval on this one (demov video above)? I positioned menus little differently than in figma. LMK if it works

**Comment by PriPatel** [comment]
Looks fine to me!

A little bonus would be to add icons to the dropdown 

'plus' icon for adding existing charts and dashboards
'clean' icon' for creating new charts and dashboards

wdyt? I can open a ticket :)

**Comment by PriPatel** [comment]
Looks good :)

**Review by rephus — APPROVED** [review]
LGTM

**Review by ZeRego — APPROVED** [review]

**Pull request merged**
