### PR TITLE
feat: format numbers with commas

### PR DESCRIPTION
**Pull request by nathaliabj**
### Pre requirements:
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #2029 
### Description:
This PR formats big numbers

### Preview:
Screenshot 2022-05-09 at 14 18 07

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
format tests are breaking for some reason :thinking: 
 ● ProjectService › format and round › formatValue should return the right format

**Comment by owlas** [comment]
Let's add more unit tests to catch these regressions!

**Comment by rephus** [comment]
Some tests are still failing, but this one in particular, needs to be updated , because you are returning now a string even when rounding doesn't happen. 

● ProjectService › format and round › formatValue should return the right format

    expect(received).toEqual(expected) // deep equality

    Expected: 5
    Received: "5"

 expect(formatValue('', undefined, 5)).toEqual(5);
      [14](https://github.com/lightdash/lightdash/runs/6355321390?check_suite_focus=true#step:7:14)7 |             expect(formatValue('percent', undefined, false)).toEqual(false);
      148 |
    > 149 |

**Comment by owlas** [comment]
@rephus @nathaliabj we probably always want this to return a string though?

**Comment by nathaliabj** [comment]
I agree with @owlas, in every scenario we always return a string except for this one, we should always return the same type. will update

**Comment by rephus** [comment]
> @rephus @nathaliabj we probably always want this to return a string though?

Yes, sorry, that is what I meant with `but this one in particular, needs to be updated` we need to update the test to accept the new string

**Comment by ZeRego** [comment]
@owlas @rephus @nathaliabj Note that my WIP PR is going to make sure the formatValue function always returns a string. 
`https://github.com/lightdash/lightdash/pull/2041` You can check my code.

**Comment by nathaliabj** [comment]
Closing as will be solved in #2033

**Comment by rephus** [comment]
> Closing as will be solved in https://github.com/lightdash/lightdash/pull/2033

InternalError: too much recursion

**Pull request closed without merging**
