### PR TITLE
fix: open threshold edit modal on click of link

### PR DESCRIPTION
**Pull request by VenkataRohan**
Closes: #9075 

Description:
Checked Schedule Delivery model is getting open when we pass scheduler_uuid as query parameter in the URL
and replicated the same for threshold_uuid. please check the below video

https://github.com/user-attachments/assets/7fb3ba24-f2d7-414a-a0d4-07da54ca0e17

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by joaoviana** [comment]
Thank you for contributing @VenkataRohan ! 

This works great! Tested with an email delivery of a threshold alert

Screenshot 2024-11-01 at 14 43 56
Screenshot 2024-11-01 at 14 44 17

Made 2 changes: 
removed the `isSync` check if it's a threshold
changed the casing of the var that tracks the uuid param (from PascalCase to camelCase)

**Review by joaoviana — APPROVED** [review]

**Comment by joaoviana** [comment]
> Hi Team, I am new to open source, can you please let me know what are the next steps?

Just seen this message @VenkataRohan 
We tend to pick up external contributions ASAP, but it also helps to message in our community's Slack channel #community-contributors if you don't hear back from us for a long time 😄

**Comment by joaoviana** [comment]
@all-contributors add @VenkataRohan for code

**Comment by VenkataRohan** [comment]
> Just seen this message @VenkataRohan We tend to pick up external contributions ASAP, but it also helps to message in our community's Slack channel #community-contributors if you don't hear back from us for a long time 😄

Hi @joaoviana 
Thanks a lot for accepting my contribution. didn't know that I can message in the slack channel thanks for the information Looking forward to contributing more to this repository.

**Pull request merged**
