### PR TITLE
feat: Add the API to get a project

### PR DESCRIPTION
**Pull request by yu-iskw**
Closes: https://github.com/lightdash/lightdash/issues/5910

### Description:
We would like to manage the API to get a project with `swagger.json`.

### CODE REVIEW

**Comment by rephus** [comment]
Sorry but a test is failing, I'm trying to figure out why..

$ yarn workspace backend build
$ tsc --build tsconfig.json
src/generated/routes.ts(890,5): error TS1117: An object literal cannot have multiple properties with the same name.

**Comment by rephus** [comment]
Ok, I know why, it seems routes.ts was incorrectly merged.

Could you generate-api again and push that change ? 

image

**Comment by yu-iskw** [comment]
@rephus I have re-generated `routes.ts` and `swagger.json`. 

By the way, we may want to have something to automatically generate the two files with husky or GitHub Actions so that we can keep them fresh.

**Comment by rephus** [comment]
@yu-iskw 

> By the way, we may want to have something to automatically generate the two files with husky or GitHub Actions so that we can keep them fresh.

Yes, I agree, we recently tried with husky, but it was creating conflicts all the time , even when routes were not changing. We need to fix this https://github.com/lightdash/lightdash/issues/5930 before we can fully automate it

**Review by rephus — APPROVED** [review]
Manually tested on render, looks good !

**Pull request merged**
