### PR TITLE
fix: Improve the `access` parameter of `CreateSpaceInProject`

### PR DESCRIPTION
**Pull request by yu-iskw**
Closes: https://github.com/lightdash/lightdash/issues/7299

### Description:
We pass an array of user UUIDs. We drop the parameters about project roles, first names and last names of users.

### CODE REVIEW

**Comment by rephus** [comment]
Duplicating PR for testing yu-iskw:improve-create-space-api

**Review by rephus — CHANGES_REQUESTED** [review]
The change makes sense, however, this API change is not compatible with our UI, which is expecting a full SpaceShare object; it is throwing a `validation error: excesss property` 

So we'll have to update the frontend request to only provide the user uuids in the `body`

image

Let me know if you're up for making this change, otherwise we can do it ourselves

**Comment by yu-iskw** [comment]
@rephus Thank you for catching up with it. I will look into the frontend side too.

**Comment by yu-iskw** [comment]
@rephus I am trying to improve the frontend too. Please tell me, If there is anything else we have to do. Though I have walked through the code of the frontend, I'm totally new to that part. I haven't completely understand what we should do for this purpose.

https://github.com/lightdash/lightdash/pull/7300/commits/a25779ec5e9346aeaae0c886e591aa54e5949adf

**Review by rephus — APPROVED** [review]
Great job, I tested this on render and everything is working fine, we can merge .

**Comment by rephus** [comment]
One of the e2e tests failed : `Should get success response (200) from GET savedChartRouter endpoints` I'm trying to understand why

**Comment by rephus** [comment]
I am running that test locally and it seems fine, I guess this is failing because I've made some changes on the render environment to test this feature manually.

**Comment by yu-iskw** [comment]
@rephus Thank you for the support!

**Comment by yu-iskw** [comment]
@rephus How should we handle the issue reported by sentry?

**Comment by joaoviana** [comment]
> @rephus How should we handle the issue reported by sentry?

Hey @yu-iskw, I've fixed it here already https://github.com/lightdash/lightdash/pull/7381 👍

**Pull request merged**
