### PR TITLE
feat: column header interactivity

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #2912 

### Description:
adds dropdown menu instead of right click

CleanShot 2022-08-22 at 21 34 33@2x

@PriPatel does this look alright? I might tweak styles to make header cell little narrow

demo:

https://www.loom.com/share/090d9155326f44c99e1365ec550f7c2e

latest screenshot:
CleanShot 2022-08-24 at 17 40 48@2x

### CODE REVIEW

**Comment by PriPatel** [comment]
looks good - so much better than the invisible right-click 😅

**Comment by rephus** [comment]
@IrakliJani is this still in draft ? are you waiting for a review ?

**Comment by IrakliJani** [comment]
@rephus its still a draft

**Comment by owlas** [comment]
is this good to review?

**Comment by IrakliJani** [comment]
@owlas yes!

**Review by owlas — CHANGES_REQUESTED** [review]
When I click on "edit" calculation or "remove" for a table calculation the modals appear and instantly disappear (see gif)

Also when I remove a custom metric the app crashes. Is this rebased on `main` it could be from a previous bug that was recently fixed.

Aug-25-2022 10-22-24

**Comment by IrakliJani** [comment]
@owlas fixed ⚡

**Review by owlas — CHANGES_REQUESTED** [review]
The table resets on closing the modals, I can't reproduce this on main

Aug-26-2022 16-22-21

**Comment by IrakliJani** [comment]
@owlas fixed

**Review by ZeRego — APPROVED** [review]

**Pull request merged**
