### PR TITLE
feat: view mode chart filters

### PR DESCRIPTION
**Pull request by rephus**
Closes: https://github.com/lightdash/lightdash/issues/3272

### Description:
[Screencast from 20-10-22 13:10:20.webm](https://user-images.githubusercontent.com/1983672/196933557-a5e4eaf1-b2fe-4925-b3d8-4b8d674947c6.webm)

### CODE REVIEW

**Comment by rephus** [comment]
I don't like how all fields disabled look. :thinking: maybe just replacing the input disable with a regular span... (might require some extra refactoring)

**Comment by TuringLovesDeathMetal** [comment]
Ya, agreed - don't love how they look. 

What if we kept them looking enabled, but just removed interactivity. And then when someone tried to click on things, we give them a message. 

Something like this: https://miro.com/app/board/uXjVPOIiJos=/?share_link_id=107715095942

**Comment by rephus** [comment]
I applied some CSS magic to change how disabled filters look. how about now ? 

image

(I haven't uploaded the code yet, I needt o manually update every component with this disabled style)

**Comment by rephus** [comment]
https://twitter.com/towernter/status/1582618095604355072

**Comment by TuringLovesDeathMetal** [comment]
^ lol 😂 

@rephus this looks awesome though!

I'm wondering if maybe we add a little warning message at the top when you open the toggle? 

Like this:
image

Let me know what you think!

**Comment by rephus** [comment]
image

**Comment by rephus** [comment]
[Screencast from 24-10-22 15:50:08.webm](https://user-images.githubusercontent.com/1983672/197541826-2e106620-718a-46b6-8ce2-8438fd23c493.webm)

**Comment by IrakliJani** [comment]
> Screencast.from.24-10-22.15.50.08.webm

perfect

**Review by IrakliJani — APPROVED** [review]

**Pull request merged**
