### PR TITLE
feat: add clickable links

### PR DESCRIPTION
**Pull request by owlas**
Closes: #2470 

This adds the ability to add one or many links to a dimension or metric. These can be accessed by clicking the dimension or metric value in the results table in the explorer on in a table visualisation on a dashboard.

The url is templated using liquidjs, which is safe. I chose to use liquidjs because it's very common that users may want to url encode the value they get from the dimension/metric to create a usable url. All these features all exist in liquidjs. I customised the delimiters to match our existing templating syntax.

The user has access to the raw value from the data warehouse `value.raw` or the formatted value, which is exactly what they see in the table in Lightdash `value.formatted` 

I'd love to provide an easy wysiwyg interface for building these templates, but for now this will do!

### Description:

Config example I've added to `jaffle_shop` (bumped in this PR)

```yaml
- name: date
        meta:
          dimension:
            type: date
            urls:
              - label: Open in Google Calendar
                url: '[https://calendar.google.com/calendar/u/0/r/day/${](https://calendar.google.com/calendar/u/0/r/day/$%7B) value.formatted |split: "-" |join: "/"}'
```

Aug-25-2022 16-17-29

### CODE REVIEW

**Review by IrakliJani — COMMENTED** [review]
code looks good to me.

removing RichBodyCell will break #2785 
> Links should appear blue, and there should be an extra item in the context menu 'Go to link' (for now!)

But looks like it was a temporary feature

**Comment by owlas** [comment]
Ah whoops, we might still want that so it's obvious that there are actions available in the context menu!! I'll add it back in

**Review by IrakliJani — APPROVED** [review]

**Comment by rephus** [comment]
I can't change a chart type after doing `explore from here` from a dashboard image

**Comment by rephus** [comment]
There are a couple of E2E errors (about context menus?) 
image

**Comment by rephus** [comment]
Is there any way to test this on render ? have you added links to jaffle shop ?

**Comment by rephus** [comment]
Next think I want to have is a table calculation that will allow me to click on  links :heart_eyes:

**Comment by TuringLovesDeathMetal** [comment]
@owlas is there anything blocking this?

**Pull request merged**
