### PR TITLE
feat: update dashboard header

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #2072

### Description:

- [x] implemented update name and description modal
- [x] added updated / updated by info
- [x] shared styles with chart page header
- [x] added share link button
- [ ] action menu: delete / duplicate / etc... (I'll use a new branch for that)

Chart / Dashboard page headers are now using the same styles 🎩 

@PriPatel wdyt about styles? anything you would like to improve?

CleanShot 2022-08-11 at 13 42 57@2x
CleanShot 2022-08-11 at 13 42 48@2x

functionality demo:

https://user-images.githubusercontent.com/962095/184107766-d165fb11-a07c-4096-a88a-9d8a7624a960.mp4

### CODE REVIEW

**Comment by IrakliJani** [comment]
I just noticed one UI bug that I'm fixing 
CleanShot 2022-08-11 at 15 01 58@2x

**Comment by IrakliJani** [comment]
and need to update e2e file

**Comment by ZeRego** [comment]
@IrakliJani this is looking great! 👨‍🍳 😗 👌 
Should we also show the space where the dashboard is on ?

**Comment by IrakliJani** [comment]
@ZeRego yup, I'll add that. I have to add action menu as well. next PR or the same PR wdyt?

**Comment by ZeRego** [comment]
> @ZeRego yup, I'll add that. I have to add action menu as well. next PR or the same PR wdyt?

@IrakliJani I would add the space info in this PR since it's already changing that component. I think is good to leave the action menu for a separate PR 👍

**Comment by PriPatel** [comment]
@IrakliJani Looks good! There might be another ticket open already for the Space name- ill just check. I also want to get rid of 'last refreshed by' so when I get confirmation, I will add it. Too much to read now!

**Comment by IrakliJani** [comment]
added spaces

CleanShot 2022-08-11 at 19 47 55@2x

**Comment by PriPatel** [comment]
Related to
https://github.com/lightdash/lightdash/issues/2932

**Review by ZeRego — APPROVED** [review]
lgtm 🎉 nice work

**Pull request merged**
