### PR TITLE
feat: hide axes lines chart

### PR DESCRIPTION
**Pull request by rephus**
Closes: #2508
### Description:

Peek 2022-07-18 17-11

### CODE REVIEW

**Comment by owlas** [comment]
@rephus is this todo with this PR? I'm getting the chart flickering every time I open the chart config tab, I guess this is because of re-rendering? https://www.loom.com/share/0e03fb412e6242259199e778978cdc86

**Review by owlas — CHANGES_REQUESTED** [review]
Screenshot 2022-07-19 at 12 58 11

Can we use the same formatting as the switch further up in the form:
* Sizing
* Right-align button first then text

**Review by owlas — CHANGES_REQUESTED** [review]
Sorry I missed it off the first review, can the toggles be on separate lines too

Merge without review after that!

**Comment by rephus** [comment]
Ok, there is an issue with sqlrunner on E2e tests, I need to fix before merging

**Pull request merged**
