### PR TITLE
feat: disable already added chart on dashboard

### PR DESCRIPTION
**Pull request by rephus**
Closes: #2394

### Description:

Peek 2022-07-18 16-01

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
@rephus Nice! I really like the comment on hover 😚 👌 

Is there a way to have the items greyed out, but still able to be added multiple times? (sorry, I realize the spec called for totally disabling them).

The reason being: eventually, we'll make it so that you can add dashboard filters, but only apply them to specific charts in your dashboard. I can imagine a scenario where you add the same chart twice to a dashboard, but with different filters applied (e.g. to compare the weekly revenue for Premium users vs. the weekly revenue for Standard users from a graph where you have both of them plotted)

If it's tricky to do in this PR, then let's just leave it as-is! and we can solve this problem when it happens :)

**Comment by TuringLovesDeathMetal** [comment]
^I'm also not sure how weird this will look...like if it'll be confusing for users that it's greyed out, but still clickable 🤔 wdyt?

**Comment by rephus** [comment]
> Is there a way to have the items greyed out, but still able to be added multiple times? (sorry, I realize the spec called for totally disabling them).

ahh, yes, I thought about this option when I read the ticket, but because we don't support individual filters I thought there was no point of adding the same chart multiple times... I'll try asking next time.

**Comment by rephus** [comment]
But actually I think we should allow that once we have filters, otherwise, as you say, it might look confusing to "click" on a disabled item. 

Implementation wise is not different to what I've done, but instead of adding a `disabled` property we might want to do `style color: GRAY` or even add  a `tick` icon on the item

**Review by owlas — APPROVED** [review]

**Pull request merged**
