### PR TITLE
chore: remove unused frontend code

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #5338 

### Description:

- used `ts-unused-exports` library to identify dead code
- adds frontend script: `yarn workspace frontend unused-exports`
- cleans up unused code

❓❓❓ question: should we fail a build if there are unused exports? ❓❓❓

### CODE REVIEW

**Comment by ZeRego** [comment]
> question: should we fail a build if there are unused exports?

@IrakliJani yes, we could make it part of the linting github action.
And to make it even better, ran it in `lint-staged` as part of the pre-commit validation.

**Comment by owlas** [comment]
Screenshot 2023-05-03 at 08 54 52

I like it 🎉

**Review by joaoviana — APPROVED** [review]
👏

**Comment by IrakliJani** [comment]
@ZeRego added both!

**Pull request merged**
