### PR TITLE
feat: analytics cross filter applied click on dashboards

### PR DESCRIPTION
**Pull request by rephus**
Closes:#2758

### Description:

Screenshot from 2022-08-24 13-12-41

### CODE REVIEW

**Comment by rephus** [comment]
@TuringLovesDeathMetal do you need any extra property on those events ?

**Comment by TuringLovesDeathMetal** [comment]
Nope! :)

**Comment by TuringLovesDeathMetal** [comment]
just kidding!

Is there a way of adding the `project_id`, and `dashboard_id` please? 🙏

**Comment by rephus** [comment]
> Is there a way of adding the `project_id`, and `dashboard_id` please? pray

Added

Screenshot from 2022-08-24 13-43-19

**Review by TuringLovesDeathMetal — APPROVED** [review]
niiiice! looks good to me :)

**Pull request merged**
