### PR TITLE
feat: projects with same name cannot be created

### PR DESCRIPTION
**Pull request by karan0handa**
Closes: #6828 

### Description:

- throw error on backend if project with the same name is created

image
 
### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by rephus** [comment]
Code looks good, but I want to test this on render in case it is breaking any e2e tests (we create multiple projects called jaffle shop for testing)

**Comment by rephus** [comment]
As I suspected, many e2e tests are failing now because we cant' create multiple projects with the same name . We'll have to update all those tests if we want to merge this feature

image

**Comment by karan0handa** [comment]
@rephus e2e locally seems to be crashing because my docker is limited to 8gb ram. Can you deploy and run it once to see if it passes?

**Comment by owlas** [comment]
Hey @karan0handa this change has more implications across the application, such as database consistency. However the team doesn't have time to provide feedback on this pull request currently. I'm closing for now

**Pull request closed without merging**
