### PR TITLE
chore: replace moment with dayjs (direct replacements)

### PR DESCRIPTION
**Pull request by karan0handa**
Related to: #6129 

### Description:

- Migrating from moment to dayjs
- There's more or less a 1-1 mapping between moment and dayjs, except for the requirement of plugins in dayjs

### Todo

- [x] [Identify all the moment methods](https://docs.google.com/spreadsheets/d/1JwPcszPjUN69Z7dSgnS0zUAP06Qywgxp1Rut_Q0t9kc/edit#gid=0) being used and figure out which ones are [direct replacements](https://github.com/iamkun/dayjs/issues/2482) and which ones aren't
- [x] Change direct replacements (trivial)
- [ ] Change non-direct replacements (other PR onwards)
- [ ] Deal with the final few icky ones
- [ ] Double-check type consistency

This [spreadsheet](https://docs.google.com/spreadsheets/d/1JwPcszPjUN69Z7dSgnS0zUAP06Qywgxp1Rut_Q0t9kc/edit#gid=0) contains all the files which are yet to be replaced with dayjs. There's lots of inter-dependencies which need to be wrangled out. For example, `formatting.tsx` has functions like `formatDate()` which are used in a lot of files. Functions like these needs to be carefully replaced. Another complication is making sure that the `moment` functions correspond to `dayjs` functions. For example, the `toString()` method behaves differently in both the libraries.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by karan0handa** [comment]
Hey @magnew. I noticed you started tests on this PR. There's still some work to be done on this before this is merge ready.

**Comment by magnew** [comment]
> Hey @magnew. I noticed you started tests on this PR. There's still some work to be done on this before this is merge ready. Do you plan to continue work on this? I'll planning to finish this by tomorrow / day-after.

Hi @karan0handa, I wanted to update it with the recent changes from main to get the tests passing. I also fixed some code styles. 

What else do you intend to do? I know there is quite a lot more moment in the system. I was going to consider this incremental progress and break the original ticket into FE and BE work remaining tasks. 

If you post a review that you intend to do more work on, it would be helpful if you just say in the description what remains to be done. Thank you!

**Comment by karan0handa** [comment]
@magnew Ah my bad. I've updated the description with todos, thanks! Essentially there are some direct replacement functions from `moment` to `dayjs` (like `moment().format`) that I'll deal with first. Then I'll deal with the non-direct replacements. I'll statically analyzed the variables using moment and they have a fairly short scope so this should be fairly easy! 

It'll be wise to run e2e at the end of each of these todo items so as to know when / what fails. I'll ask you to do it when I'm done with each todo?

**Comment by karan0handa** [comment]
@magnew I've done all the trivial changes. This can merged now. For the remaining things, I'll create a dependency graph and slowly chip away at the code. I'll do that in another PR.

**Comment by magnew** [comment]
> @magnew I've done all the trivial changes. This can merged now. For the remaining things, I'll create a dependency graph and slowly chip away at the code. I'll do that in another PR.

Ok, that sounds reasonable. For the TODOs you added to the description, can you please mark which are done? I want to make sure it's clear what has been done and what remains to be done. And Ideally what is trickier about the remaining ones so that anyone else who picks it up knows what to watch out for. Or if you do the remainder, what we're looking for. 

I'll take a close look at this and run the tests on it. Thanks for doing this, it's good to get it done!

**Comment by karan0handa** [comment]
Updated the description along the remaining information.

**Comment by owlas** [comment]
Hey @karan0handa I'm closing this PR and associated issue since we haven't had any problems with moment. dayjs is supposed to be faster but we can't attribute any performance problems to moment currently.

**Pull request closed without merging**
