### PR TITLE
fix: add expiration days on slack and email footer

### PR DESCRIPTION
**Pull request by rephus**
Closes: #6306

### Description:

Slack: 
Screenshot from 2023-09-21 17-05-55
Screenshot from 2023-09-21 17-06-14

Email:

Screenshot from 2023-09-21 17-00-48
Screenshot from 2023-09-21 17-03-33
Screenshot from 2023-09-21 17-04-57

### CODE REVIEW

**Comment by rephus** [comment]
@IrakliJani I only copied the `tr` from the email template that contains the expiration day (instead of copying the full html template with the new design). This is going to cause less conflicts if you are going to update the same template too.

**Comment by PriPatel** [comment]
Hey @rephus 
Now that we add the date at the bottom, are you able to remove it from the title? We want to use that area for body messages now!
Screenshot 2023-09-21 at 16 23 04

**Comment by rephus** [comment]
> Hey @rephus Now that we add the date at the bottom, are you able to remove it from the title? We want to use that area for body messages now! Screenshot 2023-09-21 at 16 23 04

Yeah, I noticed this change, I could easily remove it, but I didn't want to change anything that was not part of this feature, becuase @IrakliJani is also going to update the template, so it is going to cause any conflicts. 

So my suggestion is for him to either copy the full HTML and overwrite/redo my changes on his PR. or for him to also do the body on his PR and then we'll do another PR to change the rest of the style.

**Review by IrakliJani — APPROVED** [review]
@rephus looks great. you can ship this and I'll rebase my PR on top, replace whole HTML of the body and make sure your changes are include in there in my PR

**Comment by PriPatel** [comment]
@rephus @IrakliJani Thanks both!!!!

**Pull request merged**
