### PR TITLE
feat: "Ends with" option for filtering

### PR DESCRIPTION
**Pull request by muhsinkamil**
Closes:  https://github.com/lightdash/lightdash/issues/5387

### Description:

- Add ends with filter
- Similar to starts with, can multi-select items to filter

### CODE REVIEW

**Review by ZeRego — APPROVED** [review]
lgtm 🚀 

Made a small change and added unit tests for the filter grammar.
Waiting for PR checks to pass and have a final test in the PR environment.

**Comment by muhsinkamil** [comment]
Thanks @ZeRego I actually didn't understand `filterGrammer` and the filter was working on UI without those changes, That was the reason I didn't make a change there.. Is it for CLI or yaml parsing ?

**Comment by ZeRego** [comment]
@muhsinkamil the filter grammar is for filters defined in the metrics yml.
You can check these docs: https://docs.lightdash.com/references/metrics#available-filter-types

**Comment by muhsinkamil** [comment]
Oh cool, I did not know this one 👍 
Thank you !

**Pull request merged**
