### PR TITLE
Fix :  #265  Filter value doesn't match the value in the url

### PR DESCRIPTION
**Pull request by rahul3v**

### CODE REVIEW

**Comment by ZeRego** [comment]
Hi @rahul3v thanks for having a look at this bug. 
The fix is incomplete since the component expects a `Date` and the `field.value` is a `string`.
So we need to convert it to date: 
```
value={new Date(filter.value)}
```
Would be great if you could also update the CHANGELOG.md to mention the fix.

**Comment by rahul3v** [comment]
@ZeRego , Yaa I miss that :), 
Sure will update with the changes

**Comment by rahul3v** [comment]
@ZeRego, You can rebase it and merge that now, as am not able to do force-pushed via CMD, due to 2Step-Auth on my account, otherwise I have to disable it to do that

**Comment by ZeRego** [comment]
> @ZeRego, You can rebase it and merge that now, as am not able to do force-pushed via CMD, due to 2Step-Auth on my account, otherwise I have to disable it to do that

Sure, no problem 👍

**Comment by ZeRego** [comment]
Closes: #265

**Pull request merged**
