### PR TITLE
feat: Resolve issue where 'no data available' message appears initially, then data loads in explore view chart

### PR DESCRIPTION
**Pull request by anshul45**
Closes: https://github.com/lightdash/lightdash/issues/8627

### Description:
This PR Added feature where 'no data available' message appears initially, then data loads in explore view chart, as stated in the issue https://github.com/lightdash/lightdash/issues/8627

https://www.loom.com/share/f1b2f423e85e40e59fbe2d784f062723?sid=64b34c46-8090-4a5d-89c7-9fb13de8592b

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by anshul45** [comment]
Previous was: https://www.loom.com/share/7db5ab13608648b18613f272390ccbac?sid=95796b6c-5041-4dba-b4f5-e2094496ba1f

**Comment by filp** [comment]
Thank you for your pull request @anshul45!

Your approach is a step in the right direction, but I'm opting to not merge it as-is in lieu of a more comprehensive solution for loading state in the short-term; specifically something that will apply more consistently across different chart types.

**Pull request closed without merging**
