### PR TITLE
feat: reorder new dashboard tiles to bottom

### PR DESCRIPTION
**Pull request by rephus**
Closes: #2192

### Description:
Peek 2022-05-30 10-36
Peek 2022-05-30 10-39

### CODE REVIEW

**Review by owlas — CHANGES_REQUESTED** [review]
This doesn't seem to work for me. I tried a few times and I got:
* one time it added at the top
* one time it added 2 rows from the bottom
* one time it added 1 row from the bottom

See example here: https://www.loom.com/share/bb6427237462486a92c3f7d8c2d32187

**Comment by rephus** [comment]
afaik the backend always returns UTC

customer.created returns `raw` timestamp,
With useUTC:true 

image
image

By month
image


With useUTC:false (wrong ) 

image

**Comment by rephus** [comment]
I was not reordering the charts when they were added from `saved charts or explore` just on `dashboard edit` , now it works on both 
Peek 2022-05-30 11-51

**Review by owlas — CHANGES_REQUESTED** [review]
Not sure if this is related to your PR but when I hit edit, the order changes: https://www.loom.com/share/3b4809ebfad046df894ac82c22b4d805

**Review by nathaliabj — APPROVED** [review]
Looks good!, If tried adding tiles from within the dashboard, saved charts, and explorer and the tile was always added to the bottom correctly! 🚀

**Pull request merged**
