### PR TITLE
feat: export as csv style consistency

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/3721

### Description:
- updated button styles
- removed card wrapper which created an unwanted border
- wrapped radio groups in form group for better UI

before:
CleanShot 2022-11-14 at 12 47 01@2x

after:
CleanShot 2022-11-14 at 12 47 10@2x

### CODE REVIEW

**Comment by rephus** [comment]
Interesting CLi error... retrying

**Comment by rephus** [comment]
We should also unify all the different Download CSV buttons , we currently have 3. /cc @PriPatel 

Screenshot from 2022-11-14 10-24-28
Screenshot from 2022-11-14 10-25-26
Screenshot from 2022-11-14 10-25-32

**Comment by IrakliJani** [comment]
thanks @rephus, I'll go through them as well in this PR

**Comment by IrakliJani** [comment]
@rephus @PriPatel 

CleanShot 2022-11-14 at 22 01 10@2x

CleanShot 2022-11-14 at 22 06 10@2x

CleanShot 2022-11-14 at 22 06 19@2x

**Comment by IrakliJani** [comment]
I found one more CSV button in underlying data
CleanShot 2022-11-15 at 15 55 01@2x

**Review by rephus — APPROVED** [review]
LGTM as it is, if you also change the one in underlying data, even better.

**Pull request merged**
