### PR TITLE
feat: automatic run query when user hit submit on table calculation modal

### PR DESCRIPTION
**Pull request by muhammadjufry**
Closes: #4853

### Description:
Here's the video demo:
https://www.awesomescreenshot.com/video/15892921?key=319fe3ed2db7268b29b42592727a8346

### CODE REVIEW

**Comment by muhammadjufry** [comment]
Sorry for the video resolution

**Comment by rephus** [comment]
Thanks for contributing @muhammadjufry  :raised_hands: ! 

The goal for this ticket is to populate the `table calculation` values after running query, but I can see on your demo video that they are still empty.. 

image

It looks like you're triggering `runQuery` before `tableCalculations` are added to MetricQuery state, so the `runQuery` request doesn't compute it. You might need to run this after `onSave` happens (EventName.UPDATE_TABLE_CALCULATION_BUTTON_CLICKED, or EventName.CREATE_TABLE_CALCULATION_BUTTON_CLICKED)

**Review by rephus — CHANGES_REQUESTED** [review]
See comment

**Comment by muhammadjufry** [comment]
Ok will fix that!

**Comment by muhammadjufry** [comment]
Hi @rephus I have tried to add `EventName.UPDATE_TABLE_CALCULATION_BUTTON_CLICKED` and `EventName.CREATE_TABLE_CALCULATION_BUTTON_CLICKED` but it doesn't work here is the code:

`onSave({`
  `  name: getUniqueTableCalculationName(`
    `     name,`
    `     tableCalculations,`
  `   ),`
   `   displayName: name,`
   `   sql,`
`});`
`track({ name: EventName.CREATE_TABLE_CALCULATION_BUTTON_CLICKED });`

Maybe if there is any i do wrong?
Many thanks

**Comment by rephus** [comment]
> Did you mean like that, or maybe if there is any i do wrong? Many thanks

Yes sorry, I didn't explain it correctly. 

Those tracking events are useless here, they are only used to track usage on Lightdash.

This is where we add table calculations: 

- on create: https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/TableCalculationModels/CreateTableCalculationModal.tsx#L22
- on update: https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/TableCalculationModels/UpdateTableCalculationModal.tsx#L24

We pass that onCreate method as argument, which is triggered on the tablecalculation modal. 

So we want to `runQuery` after the table calculation is added , perhaps we can call `fetchResults` directly on  those update/CreateTableCalculation methods inside exploreProvider

**Comment by muhammadjufry** [comment]
No problem!, Thank you very much for your help

**Comment by muhammadjufry** [comment]
So i can invoke the fetchResult function on two file:
1. https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/TableCalculationModels/CreateTableCalculationModal.tsx#L22
2. https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/TableCalculationModels/UpdateTableCalculationModal.tsx#L24

Is that right?
Thanks

**Comment by muhammadjufry** [comment]
Hi @rephus I have try invoke the fetchResult function after the table calculation added but still didn't work i have tried many ways but still doesn't work, here is my code:

Here's some way the i have tried but still didn't work:
1. First way

2. Second way

3. Third way


Can you tell me please what i am doing wrong?, Sorry if i disturb you
Many thanks

**Comment by muhammadjufry** [comment]
Ok i will try that and will let you know, thank you very much!

**Comment by muhammadjufry** [comment]
Hi @rephus I have tired all ways you have told me except the last one because i didn't get it what do you mean by that, and still it doesn't work, i think to solve the issue we need to find function which this function does is adding the table calculation data to the results table, so we can invoke the fetchResults function on that function and i think by doing that maybe it will work

Many thanks

**Comment by muhammadjufry** [comment]
Can you tell me please on which line you are adding `options: {shouldFetchResults: true,}`

**Comment by rephus** [comment]
> Can you tell me please on which line you are adding `options: {shouldFetchResults: true,}`

I made a PR with the changes, you can take a look here: https://github.com/lightdash/lightdash/pull/4922/files .

 I'll merge my fix soon because it is a priority for this week, so I'm closing this one. But feel free to pick up a new ticket if you like. Thanks for your effort.

**Comment by muhammadjufry** [comment]
ok no problem, thank you

**Pull request closed without merging**
