### PR TITLE
feat(wip,#1132): automatically generate dbt schemas

### PR DESCRIPTION
**Pull request by owlas**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1132 

### Description:
WIP

**Simple command to generate dbt `schema.yml` file for a single model** 

* Detects local dbt profiles.yml file
* Accepts a single model name as an argument
* Uses profiles.yml to get all column names and types for the model
* Uses column names and types to generate a `schema.yml` file including Lightdash metadata

TODO:
- [ ] Run multiple models
- [ ] Work with any supported warehouse client: redshift/bigquery/snowflake/...
- [ ] Generate a useful outline `schema.yml` file including metrics and dimensions
- [ ] Create installable cli tool
- [ ] Add UI feature to download auto-generated model definition files

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [x] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by ZeRego** [comment]
@owlas This is looking good! ⭐

**Comment by owlas** [comment]
@ZeRego how difficult is it to move this to a separate cli package that we can publish to npm? 


We'd need to move `WarehouseClient` to common. We'd probably also want to move some dbt-related functions (such as parsing manifest and getting table location) to common.

**Comment by djayatillake** [comment]
This is going to be so helpful!

**Comment by owlas** [comment]
Closing until we redesign

**Pull request closed without merging**
