### PR TITLE
fix: Migrate blueprint <KeyCombo> to mantine

### PR DESCRIPTION
**Pull request by Ankush263**
Closes: #6093

### CODE REVIEW

**Comment by rephus** [comment]
The new buttons look very different color-wise, can we make it look more similar and fix the padding on the tooltip ? 

Before:
Screenshot from 2023-10-06 16-48-23

Now:




The one we use on the search bar looks better

image

**Comment by Ankush263** [comment]
Hello @rephus, I made some changes in this PR, let me know if you need anything else

**Review by rephus — APPROVED** [review]
Yeah, that looks better, thanks 

image

**Comment by rephus** [comment]
@all-contributors add @Ankush263 for code

**Pull request merged**
