### PR TITLE
feat: select warehouse before instructions

### LINKED ISSUE #3478: Improve copy for onboarding/project creation flow
### Description

currently, if you are onboarding (creating first project) heading says: "You're in! 🎉"
if you are creating another project from the settings header says: "Connect new project"

CleanShot 2022-10-12 at 15 45 50@2x
CleanShot 2022-10-12 at 15 45 52@2x
CleanShot 2022-10-12 at 15 45 59@2x
CleanShot 2022-10-12 at 15 46 01@2x

### PR DESCRIPTION
**Pull request by IrakliJani**
### Description:
- [x] moves warehouse selection step before cli instructions screen

https://user-images.githubusercontent.com/962095/195265619-0de5caae-c558-405c-a286-9530ed8abad8.mp4

closes #3478

### CODE REVIEW

**Comment by rephus** [comment]
Need to fix e2e

**Comment by rephus** [comment]
Are we not going to include a new option `Other warehouse` that says "we don't support this warehouse" and take it to a github issue or something ? What's the issue this PR closes ? 

Btw, if I create a new member on the org (without access to the other projects), I get this screen instead:

image

**Comment by IrakliJani** [comment]
@rephus I want to discuss copy of the onboarding on today's meeting and will also mention that

**Comment by IrakliJani** [comment]
@rephus e2e are passing now

> Btw, if I create a new member on the org (without access to the other projects), I get this screen instead:

created separate issue for it https://github.com/lightdash/lightdash/issues/3477

**Comment by TuringLovesDeathMetal** [comment]
niiice!

Ya, I wonder if maybe there's an `other` option which brings you to a new screen. 

And that screen says:

> We only support warehouses that have [verified dbt adapters](https://docs.getdbt.com/docs/supported-data-platforms#verified-adapters) for now. You can vote on your warehouse in our [GitHub issues](https://github.com/lightdash/lightdash/issues) or create a new issue if you can't see yours there. In the meantime, you can [try using our demo project](https://demo.lightdash.com) to test out Lightdash instead.

^Then, we'd remove the `try our demo project` from the warehouse connection screen (and jsut have it in this "sad path" screen instead)

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal 


https://user-images.githubusercontent.com/962095/195621357-f5c96aad-3920-492b-8d90-550fd3244b1a.mp4

**Review by TuringLovesDeathMetal — APPROVED** [review]
Nice! Looks good to me :)

**Pull request merged**
