### PR TITLE
fix: date/time picker timezones

### PR DESCRIPTION
**Pull request by ZeRego**
Closes: #2457 

### Description:

Note that we are now using an experimental component from Blueprint

### CODE REVIEW

**Review by owlas — CHANGES_REQUESTED** [review]
The bug is still present in the preview: https://www.loom.com/share/1a39a5403e404c1e932033dab2995147

But the new component looks great! So do the updated selects (not sure if intentional but much better)

**Comment by owlas** [comment]
Also the list of timezones isn't scrollable and makes the page super long 

Screenshot 2022-06-17 at 20 04 41

Screenshot 2022-06-17 at 20 04 54

**Comment by ZeRego** [comment]
The timezone select should be hidden, there is a [bug Blueprint when time precision property is defined](https://github.com/palantir/blueprint/issues/5393). 

@owlas how are you simulating a different timezone and what timezone are you using ?

**Comment by owlas** [comment]
@ZeRego I'm on BST (UTC+1) and every time I edit any date-time field it jumps forward an hour

**Review by owlas — APPROVED** [review]

**Pull request merged**
