### PR TITLE
feat: chart panel should take the most space

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/3607

### Description:
- [x] created new CollapsableCard component to bring consistency across pages
- [x] chart stretch
  - [x] saved chart page
  - [x] explore page
  - [x] sql runner page

https://user-images.githubusercontent.com/962095/199466392-bc1d57da-a816-4c61-8943-f35970680af5.mp4

### CODE REVIEW

**Comment by IrakliJani** [comment]
finally got the desired result

https://user-images.githubusercontent.com/962095/199701480-835acea4-7b36-4dde-86f4-41d8466de9b5.mp4

**Comment by IrakliJani** [comment]
need to fix viz table taking infinite space instead of scroll and I think its done

**Comment by ZeRego** [comment]
Seems to be a problem with big numbers viz:
Screenshot 2022-11-03 at 17 26 23

As a user, not sure how I feel about really tall charts, I kinda find them unreadable since everything is so big and I need to move my eyes/head to go from the legend to the x axis. Would rather have a drag-and-drop to adjust to my need.

Example of tall chart.
Screenshot 2022-11-03 at 17 28 37

**Comment by IrakliJani** [comment]
@ZeRego fixed bignumber height.

**Comment by IrakliJani** [comment]
@ZeRego @PriPatel right.. maybe a reasonable max will be enough there..

**Comment by TuringLovesDeathMetal** [comment]
omg it's beautiful! 

I'd also say I don't think we should have a max height 🤔 For example, if I have a horizontal bar chart with loads of options in it, I might want to stretch out the image loads? 
image

I feel like I'd rather have the option to stretch/shrink my screen to be the right size than be limited to the size I can have the chart.

**Comment by TuringLovesDeathMetal** [comment]
The sensible default sounds great. For the draggable element, I’m not sure I understand what you mean :thinking_face: RIght now, you can just drag the browser window and it makes it bigger/smaller (and it didn’t used to do this before!)

**Comment by TuringLovesDeathMetal** [comment]
ooooh makes sense. Ya, I’d leave that for now…I think this is already a massive step in teh right direction :slightly_smiling_face:

**Comment by IrakliJani** [comment]
@ZeRego @PriPatel @TuringLovesDeathMetal I addressed all bugs and this should be good to review   🤞 🤞 🤞 

@PriPatel I'm + to implement drag and drop resizing (also something @ZeRego wanted)
sensible/proportionate chart height/width also requires some work so let's avoid doing it in this PR.

**Review by ZeRego — APPROVED** [review]
lgtm 👍 

ps: The amount of changed files/code made me rely on manual testing instead of reviewing all the code. I suggest breaking down the work in multiple PRs next time

**Comment by IrakliJani** [comment]
> lgtm 👍
> 
> ps: The amount of changed files/code made me rely on manual testing instead of reviewing all the code. I suggest breaking down the work in multiple PRs next time

yep, agreed, most of the changes are css, which basically was a pandora box and it quickly got out of hand. I could have separated extracting few components as a separate PR.

**Pull request merged**
