### PR TITLE
feat: Style lists of charts and lists of dashboards

### PR DESCRIPTION
**Pull request by owlas**
Looking for input here. I restyled the dashboard and chart lists to be a bit more simple and keep all the information close together. Previously the design was very stretched on large screens.

**Before (left)** **After (right)**

<div>
Screenshot 2021-10-22 at 16 46 09
Screenshot 2021-10-22 at 16 44 55
</div>

<div>
Screenshot 2021-10-22 at 16 49 25
Screenshot 2021-10-22 at 16 44 45
</div>

### CODE REVIEW

**Comment by ZeRego** [comment]
@owlas pushed a few changes based on my comments and fixed e2e test based on these changes. Let me know what you think.
<a href="https://www.loom.com/share/8a686146013f4968a22d446c798e4e34">
    
  </a>

**Comment by owlas** [comment]
Thanks, just restarting the PR preview, failed to deploy because of dbt seed

**Comment by owlas** [comment]
This is awesome! Thanks @ZeRego 

Is there a way to hide the `description` input field? Since this is coupled to the API calls now, I'm unsure if I can just delete this from the form. I think that'll cause an error.

**Comment by owlas** [comment]
Updated, waiting for e2e tests to pass

**Review by ZeRego — APPROVED** [review]
lgtm :)

**Pull request merged**
