### PR TITLE
feat: settings restructure - project settings navbar

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #5420 

### Description:

https://github.com/lightdash/lightdash/assets/962095/e1510942-5bb4-4117-b550-b31d4861f994

### CODE REVIEW

**Comment by PriPatel** [comment]
Nice one!! I'll open a styling ticket to differentiate between headings (org / project / user) and the actual contents!

**Comment by IrakliJani** [comment]
cool! @PriPatel wdyt about these icons?
CleanShot 2023-05-30 at 21 28 32@2x

**Comment by PriPatel** [comment]
@IrakliJani Icons are great and relevant! :)

**Comment by yasmin-e** [comment]
I discussed this with @PriPatel a while back, but I think it's weird that we have these icons that let you think these are collapsable sections and when you click nothing happens 😅 

https://github.com/lightdash/lightdash/assets/67699259/e9e8dd2b-3fe0-4088-9cc8-be6a49c3005f

**Comment by yasmin-e** [comment]
when I'm in `Org settings` and switch projects, it takes me to the `Project home page` 🤔 wouldn't it be best if it behaved the same as when I'm in `Project settings`? 
For example, I want to change the palette on different projects - it ends up being many clicks 😞 I think we should take advantage of the switcher here too.

https://github.com/lightdash/lightdash/assets/67699259/7c22fc6c-39d1-4e2a-affa-bb429ac9cf22

**Comment by IrakliJani** [comment]
@yasmin-e pallets are organisation wide but what you are describing makes sense! I'll make necessary updates!

**Review by yasmin-e — APPROVED** [review]

**Pull request merged**
