### PR TITLE
fix: dashboard mentions not working sometimes and added loading state

### PR DESCRIPTION
**Pull request by anshul45**
Closes: https://github.com/lightdash/lightdash/issues/10666

### Description:
In this pull request https://github.com/lightdash/lightdash/pull/11212, I didn't add a loading state. I created a loading component that waits for useOrganizationUsers and useSpace to resolve before displaying the CommentForm.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by ZeRego — APPROVED** [review]

**Comment by ZeRego** [comment]
@anshul45 changed hook to return undefined instead of an empty array when the data was not ready. Also made the loading /skeleton just on the input so it fits nicely then there are other comments.

mentions

**Comment by anshul45** [comment]
working on it

**Comment by ZeRego** [comment]
> working on it

@anshul45 I already pushed the changes 👍

**Comment by anshul45** [comment]
Thanks for merging my request

**Pull request merged**
