### PR TITLE
fix: duplicate: added missing query param to 'getDashboardsContainingChart' endp…

### PR DESCRIPTION
**Pull request by magnew**
…oint

Closes: 

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by magnew** [comment]
https://github.com/all-contributors add @dansreis for bug and code

**Comment by magnew** [comment]
https://github.com/all-contributors add @dansreis for bug and code

**Comment by magnew** [comment]
https://github.com/all-contributors add @Shifan-Gu for bug and code

**Comment by rephus** [comment]
@all-contributors add @Shifan-Gu for code

**Comment by rephus** [comment]
https://github.com/all-contributors add @Shifan-Gu for bug

**Comment by rephus** [comment]
@all-contributors add @Shifan-Gu for bug

**Comment by magnew** [comment]
@all-contributors add @dansreis for code, bug

**Pull request closed without merging**
