### PR TITLE
fix: fixed delete dashboards from resources list

### PR DESCRIPTION
**Pull request by ayush3160**
Closes: #11121 

### Description:

Peek 2024-08-20 16-22

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by ZeRego — APPROVED** [review]

**Comment by ZeRego** [comment]
Hi @ayush3160 👋 thanks for looking into this. Do you mind also fixing the chart deletion?

**Comment by ayush3160** [comment]
Yeah Sure, Working on it.

**Comment by ayush3160** [comment]
@ZeRego , I have fixed other actions also. Please have a look and let me know If any changes are required.
Thanks

**Comment by ZeRego** [comment]
@all-contributors add @ayush3160 for code

**Pull request merged**
