### PR TITLE
feat: pie chart config - series (3/4)

### PR DESCRIPTION
**Pull request by joaoviana**
Relates to: #9567 

### Description:

Series config: UI/UX changes detailed here: https://github.com/lightdash/lightdash/pull/9593#issue-2218646974

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by IrakliJani — APPROVED** [review]
code looks good. testing locally now!

**Review by IrakliJani — CHANGES_REQUESTED** [review]
there's a regression with DnD..

before:

https://github.com/lightdash/lightdash/assets/962095/f6895175-781a-4575-99b4-d2b2577f4e90

---

after:

https://github.com/lightdash/lightdash/assets/962095/befdac57-b79a-4126-83c4-7bf2514e2db6

**Comment by joaoviana** [comment]
> there's a regression with DnD..
> 
> before:
> 
>  CleanShot.2024-04-04.at.13.34.43.mp4 
> after:
> 
>  CleanShot.2024-04-04.at.13.34.16.mp4

Thanks for spotting this @IrakliJani !

Done here:
https://github.com/lightdash/lightdash/pull/9621/commits/641995d9678435beca8b80030ea5e21fe47bf602
https://github.com/lightdash/lightdash/pull/9621/commits/8dd7fddfa207c17d0bacaf176dba381d8158241b


https://github.com/lightdash/lightdash/assets/7611706/2f689e16-27bd-47b8-b7f1-2028818db8a0

**Review by IrakliJani — APPROVED** [review]
perfection 💅

**Pull request merged**
