### PR TITLE
fix: disable github button if not enabled

### PR DESCRIPTION
**Pull request by rephus**
Closes: https://github.com/lightdash/lightdash/issues/11765

### Description:

Screenshot from 2024-10-03 09-55-06

For testing, you can force this error by blocking the /list endpoint in dev tools.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by rephus** [comment]
Should we `hide` the menu.item if feature flag is not enable,d and show error if `github not installed` (aka error on list errors)

**Comment by joaoviana** [comment]
> Should we `hide` the menu.item if feature flag is not enable,d and show error if `github not installed` (aka error on list errors)
> 
> I don't want peope saying: "This is disabled for me, but I don't even see github integrations on settings "

Agree! Maybe we can do a conditional rendering of that Menu.Item, good point 💪

**Review by joaoviana — APPROVED** [review]
Looks great! But I agree with your point above, I think we should ship that in this PR @rephus

**Comment by rephus** [comment]
image
Done

**Review by joaoviana — APPROVED** [review]

**Pull request merged**
