### PR TITLE
redesign table calculations

### PR DESCRIPTION
**Pull request by ZeRego**
Redesign table calculations + show table calculations in chart

Preview: 
<a href="https://www.loom.com/share/0915c0c755ad407d9561c01d4ea0df5f">
    
  </a>

### CODE REVIEW

**Comment by owlas** [comment]
Screenshot 2021-09-02 at 16 14 17

On safari on OSX the "add table calculation" button is overflowing

**Comment by ZeRego** [comment]
> ❌ On safari on OSX the "add table calculation" button is overflowing

Nice catch ! 👍 

Fixed ✅

**Comment by owlas** [comment]
Looks great! 

Eventually we'd ideally not have the "id" bit because the user really doesn't need to know about that. But first we should decide and fix how we handle numbers in the name. 

Alternatively we could bring in some validation for the name text box. either way let's answer that separately.

lgtm!

**Comment by ZeRego** [comment]
e2e passing here: https://github.com/lightdash/lightdash/actions/runs/1194829666

**Pull request merged**
