### PR TITLE
WIP: merged spaces v2

### PR DESCRIPTION
**Pull request by rephus**
Closes: 

### Description:
PR that contains all 3 PRs of spaces

- [feat: warn about deleted chats and dashboards on space deletion](https://github.com/lightdash/lightdash/pull/2777)
- [feat: default shared space](https://github.com/lightdash/lightdash/pull/2775)
- [feat: select space on save chart](https://github.com/lightdash/lightdash/pull/2774)

### CODE REVIEW

**Comment by ZeRego** [comment]
Found a couple of problems when I deleted all spaces available:
- dashboards in home page weren't updated ( still show deleted dashboards )
- fatal error when I refreshed the home page
- error when I tried to create dashboard from dashboards page

Screenshot 2022-07-26 at 09 47 02
Screenshot 2022-07-26 at 09 47 16
Screenshot 2022-07-26 at 09 48 01

**Comment by rephus** [comment]
> Found a couple of problems when I deleted all spaces available:


Yes, we are aware of that , but @TuringLovesDeathMetal still thinks we shoudl allow deleting all spaces ...  https://github.com/lightdash/lightdash/issues/2768#issuecomment-1193800651

**Comment by ZeRego** [comment]
> > Found a couple of problems when I deleted all spaces available:
> 
> Yes, we are aware of that , but @TuringLovesDeathMetal still thinks we shoudl allow deleting all spaces ... [#2768 (comment)](https://github.com/lightdash/lightdash/issues/2768#issuecomment-1193800651)

@rephus @TuringLovesDeathMetal what is the proposed UX if we allow to delete all spaces ? force them to create a space if they try to create a dashboard/saved chart ?

**Comment by TuringLovesDeathMetal** [comment]
I think you should be able to delete spaces, but the whole app shouldn't go into this chaos-mode. 

I'd expect:
- I delete all of the spaces
- On my homepage, everything is empty (spaces, dashboards, charts)
- If I click `create dashboard`, a pop up appears and says `create a space to put this dashboard in`, which looks similar to the `create space` modal when you're in a saved chart. 


Does that make sense??

**Comment by rephus** [comment]
> I think you should be able to delete spaces, but the whole app shouldn't go into this chaos-mode.

Sounds great, this is exactly what I wanted to know when I asked about deletion on the ticket. 

I'm fixing this chaos mode on https://github.com/lightdash/lightdash/pull/2774

Just a quick note: 

The dashboard panel doesn't even show up if there are no charts, which means, if there is nothing, all you can do is `create a space` or run query and save it on a new space

image


image

**Comment by ZeRego** [comment]
@rephus creating a dashboard from `https://lightdash-pr-2779.onrender.com/projects/08e766c8-46f1-4e91-8e1c-70b22882c632/dashboards` is still throwing an error. I would expect to behave similar to creating a chart when there are no spaces.

**Comment by rephus** [comment]
Merged individual PRs

**Pull request closed without merging**
