### PR TITLE
fix: the separator style options in number type for table calculation formatting shouldn't have % values

### PR DESCRIPTION
**Pull request by jayanand05**
Closes: #6141

### Description:
separator style options in number type for table calculation formatting shouldn't have % values

https://github.com/lightdash/lightdash/assets/113882904/8d48a7fc-6d4e-4de4-9c69-4c9d9deec14a

### CODE REVIEW

**Review by rephus — APPROVED** [review]
Nice

**Comment by rephus** [comment]
hi @jayanand05 is this ready to review/merge ? this PR is in draft

**Comment by jayanand05** [comment]
hi @rephus I think the issue was to remove the % from only the number type i removed it from all type just checking that.

**Comment by jayanand05** [comment]
@rephus, i think this was the actual issue can you look at this solution wdyt?

https://github.com/lightdash/lightdash/assets/113882904/84bc23da-10ac-4526-bfe1-0c43ed366aaa

**Review by rephus — CHANGES_REQUESTED** [review]
I actually prefer to remove it from everything, so let's keep your previous commit

**Review by rephus — APPROVED** [review]

**Pull request merged**
