### PR TITLE
feat: added a copy sql button when card is closed

### PR DESCRIPTION
**Pull request by cooldude6000**
Closes: #10602

solves issue #10602 

### Description:

https://github.com/user-attachments/assets/f981297e-3ce8-48b6-abe4-32c66b921461

-----

This Is WORKING now. It WILL copy the SQL too, unlike the last time😂. (#10717)

### Reviewer actions

- [x] I have manually tested the changes in the preview environment
- [x] I have reviewed the code
- [x] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by cooldude6000** [comment]
@joaoviana

**Review by joaoviana — CHANGES_REQUESTED** [review]
Could you add these changes? 
- only appear on hover if the card is closed 
- should be next to the title `SQL`, instead of being on the far right 
- perhaps `title` is a `prop` that can take a `ReactNode`?

**Comment by cooldude6000** [comment]
Hi @joaoviana ,



https://github.com/user-attachments/assets/28c89ba2-3819-46af-b98a-77bb3a3dc4dd




**NOW** :
> only appear on hover if the card is closed

The copy button will be visible ONLY when card is **CLOSED** && it is **HOVERED**

> should be next to the title SQL, instead of being on the far right

It is now😅


lmk if anything to change


Ps: Regarding the changes in SqlCard.tsx file : I removed all the changes made in it and it is now the exactly same file like (https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx) . I DID NOT make any changes to it (i mean, i _removed_ the ones I did in my previous commit and the file is back to default). I made changes ONLY in CollapsableCard.tsx.

**Comment by cooldude6000** [comment]
Also, 
> perhaps `title` is a prop that can take a `ReactNode`?

Is it just changing:

**FROM**:

`title: string;` _(Line 55 of CollapsebleCard.tsx)_

TO:

`title: React.ReactNode` _(Line 55 of CollapsebleCard.tsx)_

?

**Comment by cooldude6000** [comment]
@joaoviana

**Comment by joaoviana** [comment]
made a few changes here @cooldude6000. 

For future reference, we should ensure that components in `common` have a general implementation and act as a skeleton for the other components that reuse them. 
So in this PR, I've added an optional `ref` prop that can be passed so that we can track the on-hover effect 
Then on the SQL card component I add `headerElement` and keep this logic isolated in the component that takes care of it

Thanks for contributing @cooldude6000 !

**Review by joaoviana — APPROVED** [review]

**Pull request merged**
