### PR TITLE
filtering joins to only include tables from which dimensions and metrics are selected

### PR DESCRIPTION
**Pull request by djayatillake**
Concern is that for a given dwh it is possible that table scans will happen for all tables joined even if dimensions and metrics are not chosen from them, thus slowing down the query and increasing cost for the customer.

Looker does not do this, it only joins tables with dimensions and metrics selected (looker allows for metrics to be defined with fields from multiple tables so it would take all tables used in a given metric), unless you purposefully ask for a table to be always joined. I don't believe this concept of always joined exists in Lightdash now and could be handled with an additional section such as sqlAlwaysJoins which takes these from the explore.alwaysJoinedTables assuming it was implemented this way.

If in the future a metric can be defined from multiple tables in Lightdash and therefore metric.table is then an array, this code would need to be adapted.

### CODE REVIEW

**Comment by djayatillake** [comment]
I couldn't get the app to run from the codespaces dev environment, when I ran yarn dev the browser link opened a new tab but Lightdash didn't load. The tests passed though.

**Comment by owlas** [comment]
Thanks this looks great!

**Comment by owlas** [comment]
@all-contributors add @djayatillake for code

**Comment by djayatillake** [comment]
what does the docker check fail mean?

**Comment by owlas** [comment]
@djayatillake could you enable the option to "allow changes from maintainers" - I want to push some tests to this branch.

**Comment by owlas** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by owlas** [comment]
Closing for #905

**Pull request closed without merging**
