### PR TITLE
fix: timestamp selection for is between filter

### PR DESCRIPTION
**Pull request by yasmin-e**
Closes: #4825 

### Description:

https://user-images.githubusercontent.com/67699259/228542530-908224e6-7124-42f4-9e78-5ed51f66d9c5.mov

### CODE REVIEW

**Review by owlas — CHANGES_REQUESTED** [review]
This widget uses milliseconds but they cannot be set in the widget (only seconds granularity).

In the `is equal to` we remove the milliseconds and always set them to zero. we should do the same here for consistency

Screenshot 2023-03-30 at 10 36 39


--- 
A common use case for this widget is looking at times on the same day. But in the current date picker you can't set the start and end date the same. I should be able to compare times on the same day (is between 7am and 7pm on Tuesday).

Also after picking the end date, it auto-closes the date picker, which is annoying since I might want to set the time after picking the date.

Screenshot 2023-03-30 at 10 37 43

**Comment by yasmin-e** [comment]
> This widget uses milliseconds but they cannot be set in the widget (only seconds granularity).
> 
> In the `is equal to` we remove the milliseconds and always set them to zero. we should do the same here for consistency
> 
> Screenshot 2023-03-30 at 10 36 39
> 
> A common use case for this widget is looking at times on the same day. But in the current date picker you can't set the start and end date the same. I should be able to compare times on the same day (is between 7am and 7pm on Tuesday).
> 
> Also after picking the end date, it auto-closes the date picker, which is annoying since I might want to set the time after picking the date.
> 
> Screenshot 2023-03-30 at 10 37 43

- [ ] Milliseconds in the picker and set to 0
- [ ] Same day range
- [ ] Picker does not close on selection

**Comment by hamzahc1** [comment]
Can we make this look a bit cleaner and friendly by removing the seconds altogether? Hours and minutes should be sufficient... ?

**Comment by yasmin-e** [comment]
> I'm not sure if you're able to reproduce this. I can select the same date now. But the behaviour when you "go backwards" is that it seems to extend the date range in that direction.
> 
> In this gif I've set a range in the future, and it's really hard to change my range to just be a single date in the past. Not sure what I'm doing wrong. This might be the component but I found it unintuitive.
> 
> Mar-30-2023 16-50-42 [ Mar-30-2023 16-50-42 ](https://user-images.githubusercontent.com/11660098/228893207-9442d82f-e13f-4a3b-8351-beaf878bccca.gif) [ ](https://user-images.githubusercontent.com/11660098/228893207-9442d82f-e13f-4a3b-8351-beaf878bccca.gif)

I posted about this in Blueprint's github discussion https://github.com/palantir/blueprint/discussions/6052

**Pull request merged**
