### PR TITLE
docs: amend typo for LIGHTDASH_LOG_LEVEL env

### PR DESCRIPTION
**Pull request by dmattia**
### Description:

Noticed while deploying

### CODE REVIEW

**Comment by rephus** [comment]
Thanks for your contribution, the change looks good, unfortunately I can't merge this until the PR and commit follow our naming convention (a test is failing), https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#commit--pull-request-naming-conventions
Could you make another commit (it can be empty) so we can squash the commit and use the right prefix (fix:) ?

**Review by rephus — DISMISSED** [review]
See comment above

**Review by joaoviana — CHANGES_REQUESTED** [review]
hey @dmattia, could you also do apply this change to: https://github.com/lightdash/lightdash/blob/main/docs/docs/self-host/customize-deployment/configure-logging-for-lightdash.mdx#L16C5-L16C5
Thanks for spotting this typo!

**Comment by joaoviana** [comment]
Thanks again for contributing @dmattia, I've pushed the small change I requested yesterday, will merge as soon as build is ready 😄

**Comment by joaoviana** [comment]
@all-contributors add @dmattia for doc

**Review by joaoviana — APPROVED** [review]

**Pull request merged**
