### PR TITLE
fix: focus on editable text on pencil icon click

### PR DESCRIPTION
**Pull request by cooldude6000**
solves issue #10618

Closes: 
#10618 
### Description:

https://github.com/lightdash/lightdash/assets/143312648/f132126b-31e3-4144-af2d-d1e09a69cb01

### Reviewer actions

- [x] I have manually tested the changes in the preview environment
- [x] I have reviewed the code
- [x] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by cooldude6000** [comment]
Sorry I didnt add the PR type

**Comment by cooldude6000** [comment]
I'm unable to change this. It's saying that i'm semantic smthn

**Comment by joaoviana** [comment]
> I'm unable to change this. It's saying that i'm semantic smthn

Hi @cooldude6000, thank you for contributing! All you need is to amend the commit message to be on the conventional commit message format. So like: `fix: ...`
This only happens on PRs with one commit message. LMK if you need some pointers, but it should _just work_ with `git commit --amend`>`git push -f`

**Comment by joaoviana** [comment]
@all-contributors add @cooldude6000 for doc

**Review by joaoviana — APPROVED** [review]
Thanks for adding this improvement to our user experience @cooldude6000 ! E2E tests and manual testing look great!

**Pull request merged**
