### PR TITLE
fix: error when updating color palette

### PR DESCRIPTION
**Pull request by Chrischuck**
Closes: #4673 

### Description:
Frontend was passing too much data to the backend and thus getting a validation error

https://user-images.githubusercontent.com/13311268/222781654-a1feff40-2518-49e6-8f79-21ccda3f16e8.mov

### CODE REVIEW

**Comment by owlas** [comment]
Amazing work on all these PRs @Chrischuck - I'm getting through them one by one!

**Review by owlas — CHANGES_REQUESTED** [review]
This signature should also accept `UpdateOrganisation` - not sure how this passed type checks: 

```
updateOrgQuery = async (data: Organisation)
```

**Comment by Chrischuck** [comment]
Thanks @owlas! made those changes.

**Review by IrakliJani — APPROVED** [review]
tested locally and works as expected, great work @Chrischuck 🙌 🙌 🙌

**Pull request merged**
