### PR TITLE
fix: create and join on multiorg

### PR DESCRIPTION
**Pull request by rephus**
Closes: #4824
### Description:

Before:

[Screencast from 16-03-23 16:06:06.webm](https://user-images.githubusercontent.com/1983672/225660173-83a4988d-e541-445e-af1c-484d2bac660a.webm)

After:

[Screencast from 16-03-23 16:06:48.webm](https://user-images.githubusercontent.com/1983672/225660192-ba890fea-883e-49a1-b13d-1a98875c3acb.webm)

### CODE REVIEW

**Comment by buger** [comment]
Which is the latest working version? Thanks!

**Comment by zamiang** [comment]
Is there an update when this will get merged added to docker? We are setting up lightdash for our (one) org and this is blocking us from being able to get started.

**Comment by rephus** [comment]
hi @buger I think the last version without this bug was `0.453.0`

@zamiang I'll try merging this today

**Pull request merged**
