### PR TITLE
refactor: refactored the token copy component, to include every param…

### PR DESCRIPTION
**Pull request by Ifunanyacollins**
…ter required by lightdash cli

Closes: #4365 

### Description:
Refactored the personal access token copy component to include all parameters required by the Lightdash CLI.
Screenshot 2023-02-05 at 19 36 36

### CODE REVIEW

**Review by IrakliJani — COMMENTED** [review]
Hi @Ifunanyacollins thanks for opening a PR 🙌 🙌 🙌 

I have few improvements in mind.

1. you can get an URL of the site, instead of having a tab switcher for different Lightdash instances based on the regions. best way to do that is to get site url from `useHealth()` hook. here's a an example:
```
  const health = useHealth();
  health.data?.siteUrl
```
2. let's keep token input and add CLI Auth code input as well (both copyable). here's a UI that I think will be the best

CleanShot 2023-02-06 at 16 14 19@2x

**Comment by hamzahc1** [comment]
@all-contributors add @Ifunanyacollins for code

**Comment by Ifunanyacollins** [comment]
@IrakliJani Confirming that this meets the requirements?
Screenshot 2023-02-06 at 14 23 51

**Comment by IrakliJani** [comment]
@Ifunanyacollins this looks great!!! there are some merge issues, can you rebase on main so I can approve and ship?

**Comment by Ifunanyacollins** [comment]
@IrakliJani Done, all good?

**Comment by IrakliJani** [comment]
@Ifunanyacollins did you push the updated branch? I can still see the unrelated commits
CleanShot 2023-02-06 at 18 37 13@2x

**Comment by Ifunanyacollins** [comment]
@IrakliJani  Yeah, I pushed the updated branch.

**Comment by IrakliJani** [comment]
@Ifunanyacollins I can still see extra commits and an unnecessary diff. happy to help resolve this. you can give my user write access to your forked repo

**Comment by Ifunanyacollins** [comment]
@IrakliJani sent you a collaborator invite, thanks .

**Comment by IrakliJani** [comment]
hey @Ifunanyacollins just pushed a new branch to your forked repo.

feel free to either open a new PR from that branch (https://github.com/lightdash/lightdash/compare/main...Ifunanyacollins:lightdash:fix/access-token-copy-to-cli-command?expand=1) and close this one

...or "force push" `fix/access-token-copy-to-cli-command` to this branch

**Comment by Ifunanyacollins** [comment]
@IrakliJani created a new PR, closing this. Thanks for helping out, much appreciated!

**Pull request closed without merging**
