### PR TITLE
docs: temporarily hide Codespaces section in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by nmwur**
### Description:
Temporarily hide Codespaces section in `CONTRIBUTING.md` until Codespaces is working

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by owlas** [comment]
Could you add a note in the comment about why it's commented out @nmwur ?

**Review by owlas — CHANGES_REQUESTED** [review]
Could you add a note in the comment about why it's commented out @nmwur ?

**Comment by nmwur** [comment]
Added the note @owlas

**Review by joaoviana — CHANGES_REQUESTED** [review]
Hi @nmwur ! Could you either rebase from `main` or just reset your commits so that only the change to CONTRIBUTING.md is added? 

Thanks!

**Pull request closed without merging**
