### PR TITLE
style: floating test and compile button for project settings

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/3746

### Description:
- [x] add floating card for "Test & Compile"
- [x] keep the project creation flow form as is.
- [x] some style cleanups

https://user-images.githubusercontent.com/962095/206716008-97dd2105-09d3-4478-ad1d-6d35a55bdc78.mp4

### CODE REVIEW

**Review by ZeRego — APPROVED** [review]
Everything good from code perspective 👍 
Going to let @PriPatel approve the design part

**Comment by PriPatel** [comment]
Nice @IrakliJani !
Only comment is that the pinned section used to take up the whole width of the page, (excluding the sidebar)  rather than be the same width of the form. Something like the attached... wdyt?
Screenshot 2022-12-16 at 10 48 49

**Comment by IrakliJani** [comment]
@PriPatel can you have a look to the video below...
btw, this is exactly how it worked before.
when I moved pages around it just broke and simplified to not have a floating version.

I don't like that it covers on top of the sidebar which has a small chunk of footer (version number) and documentation link.
https://user-images.githubusercontent.com/962095/208455465-d15f3867-6217-466a-862f-afdf527474b6.mp4

**Comment by IrakliJani** [comment]
@PriPatel yep!
just one thing there.

has a weird bounce effect when I off-scroll. but that's whole different issue...
https://user-images.githubusercontent.com/962095/208475165-bea04436-a6df-4987-a8f2-f8440a65eec5.mp4

**Comment by PriPatel** [comment]
@IrakliJani lol yeah its a strange bounce effect! But overall the pinned bit is looking better! 💪

**Comment by IrakliJani** [comment]
@PriPatel yep, I'm gonna ship this as is, and I want to make a change for the app frame to be fixed, and only content scroll to bounce instead. its been bothering me for a while and is quite annoying in certain pages

**Pull request merged**
