### PR TITLE
fix: add top border for table header

### PR DESCRIPTION
**Pull request by CVamsi27**
Closes: #5495 
Closes: https://github.com/lightdash/lightdash/pull/5778

### Description:
Added top border for tables

### ScreenShot:
image

### CODE REVIEW

**Comment by CVamsi27** [comment]
@IrakliJani 
What do you mean by pin table column? Screenshot would be helpful

**Comment by IrakliJani** [comment]
@CVamsi27 here's the screenshot. lmk if you need help!
CleanShot 2023-06-06 at 13 50 46@2x

**Comment by CVamsi27** [comment]
@IrakliJani 
Fixed the issue
image

**Comment by IrakliJani** [comment]
@all-contributors add @CVamsi27 for code

**Review by IrakliJani — APPROVED** [review]
looks great @CVamsi27 ! thanks for contributing to Lightdash ⚡

**Pull request merged**
