### PR TITLE
feat: add project id to space analytics

### PR DESCRIPTION
**Pull request by rephus**
Closes: #2973

### Description:

From rudderstack: 

Screenshot from 2022-08-23 10-05-02

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
niiiiice! @rephus is this included in `space created`, `space updated` and `space deleted`? Or only `space created`?

**Comment by rephus** [comment]
> niiiiice! @rephus is this included in `space created`, `space updated` and `space deleted`? Or only `space created`?

All of them 👌

**Review by TuringLovesDeathMetal — APPROVED** [review]
yay, data!

**Pull request merged**
