### PR TITLE
feat: add search to user management table

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: #8413 

### Description:

Can search now by: 
* first name
* last name
* email
* role

with fuse.js (same way we do for explores)

Ideally we want the `users` query to accept a query param but this works as a v1 for now (we would like as well to support pagination which can be done on a separate ticket)

Demo:

https://github.com/lightdash/lightdash/assets/7611706/4fc2c5dd-0ef7-4fe5-801c-3400382429f1

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by IrakliJani — APPROVED** [review]
nice!

**Comment by IrakliJani** [comment]
restarting render deploy

**Review by IrakliJani — CHANGES_REQUESTED** [review]
actually there's a build error
CleanShot 2023-12-27 at 15 23 35@2x

**Comment by joaoviana** [comment]
> actually there's a build error CleanShot 2023-12-27 at 15 23 35@2x

just made the change! ty 🙏

**Review by IrakliJani — APPROVED** [review]

**Pull request merged**
