### PR TITLE
test: create project e2e tests

### PR DESCRIPTION
**Pull request by rephus**
Closes: 

### Description:

Peek 2022-06-08 09-56

### CODE REVIEW

**Comment by rephus** [comment]
For DB passwords we can use `github secrets` and add it to `CYPRESS` env

**Comment by rephus** [comment]
The tests are almost done, we are just missing a few things around security and completeness, adding new warehouses should be trivial. 

- [ ] Add existing postgres credentials as `secrets` on this github project, so we can use `cy.env` to get variables, at least for passwords ( I don't have permissions) 
- [ ] Add credentials for biquery database with jaffle shop
- [ ] Add credentials for snowflake
- [ ] Add credentials for databricks ??

I'm sure you can quickly help with any of those missing points

**Review by ZeRego — APPROVED** [review]
code looks good, gj 👍
Should we rebase and update selectors before merge ?

**Comment by rephus** [comment]
Replaced by https://github.com/lightdash/lightdash/pull/2392

**Pull request closed without merging**
