### PR TITLE
docs: correct typos 

### PR DESCRIPTION
**Pull request by smoens**
### Pre requirements:
- [X] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Description:
Small typo fixes

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [X] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by hamzahc1** [comment]
@all-contributors add @smoens for docs

**Review by ZeRego — APPROVED** [review]
Thanks for fixing these :)

**Comment by ZeRego** [comment]
@all-contributors add @smoens for docs

**Comment by ZeRego** [comment]
https://github.com/all-contributors add @smoens for docs

**Comment by ZeRego** [comment]
@all-contributors add @smoens for docs

**Pull request merged**
