### PR TITLE
feat: add header and update main buttons

### PR DESCRIPTION
**Pull request by nathaliabj**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #2087 

### Description:
this PR updates the header with its variations for edit/explore modes.

### Edit mode
Screenshot 2022-05-13 at 11 06 25

### explore mode
Screenshot 2022-05-13 at 12 17 35

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
If you scroll down, the `save changes`button will appear on top of the header 
image

**Comment by rephus** [comment]
I opened a chart from /home and I got this screen, which looks like a mix of explore and view
image

**Comment by rephus** [comment]
From the code, isViewMode looks always hardcoded to fase, so I can't test it , is that right ?  eg: opening a chart on /home opens a chart in Edit mode...

**Review by rephus — COMMENTED** [review]
Code looks ok, there are a few TODOs for later . I think @ZeRego has more context about this feature to review the code

**Comment by PriPatel** [comment]
Hey I noticed that the spacing between the pen and the name of the chart here is a bit inconsistent? If Ive misunderstood and this is something that will be rectified when everything comes together, ignore me!!
Screenshot 2022-05-13 at 11 50 29

**Comment by nathaliabj** [comment]
> From the code, isViewMode looks always hardcoded to fase, so I can't test it , is that right ? eg: opening a chart on /home opens a chart in Edit mode...

@rephus correct, at the moment it is all hardcoded as we do not have a view mode yet. so this is part of something we can 🐑 without breaking the app

**Comment by nathaliabj** [comment]
I have updated the header to have `height: 70px` as per @PriPatel request

**Review by ZeRego — APPROVED** [review]

**Pull request merged**
