### PR TITLE
feat: explore card action item styles

### PR DESCRIPTION
**Pull request by IrakliJani**
related to: #6064

### Description:

CleanShot 2023-06-28 at 20 27 22@2x
CleanShot 2023-06-28 at 20 27 26@2x
CleanShot 2023-06-28 at 20 27 30@2x
CleanShot 2023-06-28 at 20 27 46@2x

### CODE REVIEW

**Comment by IrakliJani** [comment]
hey @PriPatel, want a designer's eye on this before I open up this PR for engineers

**Comment by PriPatel** [comment]
Screenshot 2023-06-28 at 12 57 06
@IrakliJani should the change affect these buttons too? (asking because I can see that the SQL runner button has been updated too!)

**Comment by joaoviana** [comment]
Reviewed: 
- adding filters and using the color picker on chart config, table config, done ✅ 

Getting a z-index error on big values tho: 

https://github.com/lightdash/lightdash/assets/7611706/3eacdfd0-d0de-47b9-a74c-0906656069e8

**Review by joaoviana — APPROVED** [review]
Cool! tested all scenarios, thanks!

**Pull request merged**
