### PR TITLE
fix: unlock clipboard copy when visualising tables

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: #6193 

### Description:

When visualising tables, the `ValueCell` component that currently uses `useHotKeys` would allow the copy of the `Cell` value if user pressed `mod + c`. However, this is blocking the copy-to-clipboard functionality everywhere else that is not a `ValueCell`. 
I believe the usage of the `useHotKeys` is affecting the other elements due to the way we're implementing the `ValueCellMenu`+`ValueCell`. 

Instead of adding the `onKeyDown` events to the `td` elements, we listen to: 
* is isMenuOpen truthy
* if user presses the copy keyboard shortcut (we now use `getHotkeyHandler`  https://mantine.dev/hooks/use-hotkeys/#targeting-elements )

NOTE: `td` elements aren't focusable by nature, so this addresses that

Don't have a screen-recording bc Quicktime player + keyboard shortcuts aren't working as expected for me. PLease use Render to review UX

### CODE REVIEW

**Review by IrakliJani — COMMENTED** [review]
@joaoviana 
makes sense and code looks great. but we also have another place where we should be having the same problem. check `packages/frontend/src/components/common/Table/TableProvider.tsx`

**Comment by joaoviana** [comment]
> @joaoviana makes sense and code looks great. but we also have another place where we should be having the same problem. check `packages/frontend/src/components/common/Table/TableProvider.tsx`

we don't have that problem from what I've tested! But will double-check 👍

**Comment by joaoviana** [comment]
> @joaoviana makes sense and code looks great. but we also have another place where we should be having the same problem. check `packages/frontend/src/components/common/Table/TableProvider.tsx`

thanks for spotting this @IrakliJani , it was working absolutely fine in dev mode locally, but not in Render 🤯 

Removed that usage and replaced with the other handler instead, and all working fine 👍

**Review by IrakliJani — APPROVED** [review]
looks good!

**Pull request merged**
