### PR TITLE
fix: only show selected tables on validation

### PR DESCRIPTION
**Pull request by rephus**
Closes: #5942

### How to replicate when selecting tables

I introduce an error on payments table that was appearing on validation.

When  selected customers/orders (not payments): 

Screenshot from 2023-06-20 16-53-17

Before:

Screenshot from 2023-06-20 16-53-12

AFter:

Screenshot from 2023-06-20 16-53-34

Logs: 
Screenshot from 2023-06-20 16-53-46

### How to replicate with tags

I added a tag to orders

Screenshot from 2023-06-20 17-00-46

I selected that tag

No "payment errors":

Screenshot from 2023-06-20 17-00-40

### CODE REVIEW

**Comment by ZeRego** [comment]
The problem is that those tables can be joined. So showing the errors would make sense. 
The table selection configuration is just to determine what tables/explores are available in the tables page.

**Review by TuringLovesDeathMetal — APPROVED** [review]
niceee! thank you!

**Review by ZeRego — CHANGES_REQUESTED** [review]
(see previous comment)

**Comment by rephus** [comment]
> The table selection configuration is just to determine what tables/explores are available in the tables page.

Yeah, he is right, this mainly affects visibility in the explore, but we still compile and generate errors (that's why they appear on validation) 

Should we then close this issue without merging ? @TuringLovesDeathMetal

**Comment by rephus** [comment]
By default it was not showing "orders" if orders was disabled, but payments was selected (with a join). So I made some changes in the code to show joined tables (but only 1 level, without recursion) 

Screenshot from 2023-06-21 13-15-30

Screenshot from 2023-06-21 13-33-52

**Review by ZeRego — APPROVED** [review]
lgtm 👍 
would be good to have a unit test

**Pull request merged**
