### PR TITLE
feat: sql on reference user attribute

### PR DESCRIPTION
**Pull request by rephus**
Closes: #6413

### Description:

Screenshot from 2023-07-26 15-55-38

If attribute does not exist 
Screenshot from 2023-07-26 15-55-43

If attribute exists: 

Screenshot from 2023-07-26 16-29-04

### CODE REVIEW

**Comment by owlas** [comment]
testing the preview now

**Comment by owlas** [comment]
Hey @rephus one thing I just bumped into we spoke about on the original spec, if I put this in a sql_on:

```
   - name: orders
     description: >-
       This table has basic information about orders, as well as some derived
       facts based on payments
     meta:
       joins:
         - join: customers
           sql_on: ${customers.customer_id} = ${orders.customer_id} AND ${customer_id} = ${lightdash.attributes.jaffle_cx_id}
```

So here I wanted to restrict orders based on the customer id. But if I query orders, it doesn't limit unless i choose a field from the customers table. that's because we conditionally use the join logic depending on if we reference the table.

I think this is ok and we should probably have `required` field on the join as a separate ticket:

```
joins:
  - join: table
    sql_on: ...
    required: true
```

and we'll always join the table.

What do you think?

**Comment by rephus** [comment]
> But if I query orders, it doesn't limit unless i choose a field from the customers table. 

Is that not the point of the join?, if you want to always filter, then you should be using the `sql_filter` we already implemented.

**Comment by owlas** [comment]
Agreed!

**Review by owlas — APPROVED** [review]
Tested
-  missing attribute
- attribute exists but not assigned to user
- attribute exists and does filtering

**Pull request merged**
