### PR TITLE
fix: update chart name on save as

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1230

### Description:
Fixes the chartName when saving a new chart. A fix on the usage of the value in the `EditableText` component https://blueprintjs.com/docs/#core/components/editable-text in combination with `useEffect`

Using the `alwaysRenderInput` makes no difference. 

This component is also used in DashboardHeader , I made sure the component is also working there 

### Preview:

Mar-24-2022 13-55-36

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by ZeRego** [comment]
Why are there no PR checks ? 🤔

**Review by owlas — APPROVED** [review]

**Comment by owlas** [comment]
redeploying!

**Comment by rephus** [comment]
@owlas can we merge this now ? or are we still having issues with this PR

**Review by owlas — CHANGES_REQUESTED** [review]
I managed to crash this in the PR preview, 

I'm checking prod now because I'm not sure these changes have caused it.

Screenshot 2022-03-28 at 10 58 01

**Comment by owlas** [comment]
Can't reproduce the error. merging!

**Pull request merged**
