### PR TITLE
feat: UI for pdf image delivery option

### PR DESCRIPTION
**Pull request by magnew**
Closes: #6678

### Description:

UI for choosing to send a PDF in a scheduled delivery. Backend is already checked in. 

I followed the existing pattern in this form, but I don't really like the way we are integrating with useForm. We could make this better.

### CODE REVIEW

**Comment by hamzahc1** [comment]
I'm a bit confused by this UI: 
CleanShot 2023-09-07 at 21 26 10@2x

Is the option now for the user: 
- Deliver an image 
- Deliver an image and a PDF? 

Why would I want the image and the PDF? wouldn't it be one or the other ?

**Comment by magnew** [comment]
> I'm a bit confused by this UI: CleanShot 2023-09-07 at 21 26 10@2x
> 
> Is the option now for the user:
> 
> * Deliver an image
> * Deliver an image and a PDF?
> 
> Why would I want the image and the PDF? wouldn't it be one or the other ?

It does indeed deliver the image as a PDF *and* an image in the email. The main request for this was from users that were having issues with images being stripped out of emails by their email servers. But it's a good point, it's a bit redundant. @TuringLovesDeathMetal, I think you were talking to the customer. This was the intent, right?

**Comment by TuringLovesDeathMetal** [comment]
Ya, this was the intent...but I do understand what hamzah means...

What about we make the toggle `Deliver image as PDF attachment` so it's either embedded, or a PDF attachment, but not both. 

Sorry, to change this, @magnew

**Comment by PriPatel** [comment]
To keep the interface less cluttered, there could instead be 3 options in the dropdown for format, rather than an additional toggle.
- csv
- Image (pdf)
- image (jpeg)

**Comment by TuringLovesDeathMetal** [comment]
^Priyanka to the rescue. Ya, I'm down for that suggestion!

**Comment by rephus** [comment]
^ (having a new format / choose between image OR pdf ) introduces some extra complexity on the scheduler backend logic. 

But if you're happy with this approach, we can change it

Remember we have another ticket to `add images/csv as an attachment` instead of using links, not sure if this new design is compatible .

**Review by rephus — APPROVED** [review]
Code looks good to me, fix testes and then we can merge (we will revisit this UI in the future if we need to )

**Comment by magnew** [comment]
> Code looks good to me, fix testes and then we can merge (we will revisit this UI in the future if we need to )

@hamzahc1, @PriPatel, It sounds like we talked about this in person last week and we'd rather check this in an have some solution working for people than wait to do the extra work. I'm going to merge this now and we'll revisit with the upcoming change Javi mentioned.

**Pull request merged**
