### PR TITLE
feat: migrate create dashboard modal to mantine

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: N/A

### Description:

Migrate modal to mantine

Screen recording

https://github.com/lightdash/lightdash/assets/7611706/83c4853f-b01c-4ec3-8e17-bfdb299d5b82

### CODE REVIEW

**Review by PriPatel — CHANGES_REQUESTED** [review]
The `create space` button feels too dominant - it makes me think that this is a mandatory stage of the process. Its more appropriate like this:
Screenshot 2023-09-29 at 17 04 46

**Comment by joaoviana** [comment]
> Woooooooopwoooop! One comment: The `create space` button feels too dominant - it makes me think that this is a mandatory stage of the process. Its more appropriate like this: Screenshot 2023-09-29 at 17 04 46

Nice @PriPatel, thanks for the review, here is the updated design!

https://github.com/lightdash/lightdash/assets/7611706/dcfe6b91-2f10-4bd3-985a-18f2eab2c717

**Review by IrakliJani — CHANGES_REQUESTED** [review]
@joaoviana tested and looks great and code looks great as well. there's just one weird behavior that I've noticed

https://github.com/lightdash/lightdash/assets/962095/fe3c56b0-5a69-4345-85d0-175eedf9b7bb

**Comment by PriPatel** [comment]
Opened an issue to replace the 'create new space' button later! 
https://github.com/lightdash/lightdash/issues/7278

**Review by PriPatel — APPROVED** [review]

**Pull request merged**
