### PR TITLE
feat: Add AWS SES support to email client

### PR DESCRIPTION
**Pull request by gpdenny**
Closes: #11463 

### Description:
Add support for AWS SES transport in email client.

Followed the same configuration / client convention as with S3.
(If there are further integrations with AWS I think it would be more appropriate to create a global configuration for AWS, instead repeating per service, as this is more likely to match how people write policies. Didn't want to potentially make breaking changes here to do that.)

Tested locally with Localstack and in a sandbox environment in AWS.
Also tested SMTP locally to ensure no regressions.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by owlas** [comment]
Hey @gpdenny thanks for this PR, at a quick glance it looks excellent. I'm going to chat with the team about whether we want to maintain this. We intentionally chose to use SMTP credentials for the broadest compatibility. However I see the benefits of eliminating long lived SMTP credentials.

Let me get back to you next week!

**Comment by gpdenny** [comment]
Hi @owlas just following up on this one :pray: Any thoughts on maintaining?

**Comment by hamzahc1** [comment]
Hi @gpdenny this looks like a good PR! The team is a bit slammed at the moment so we haven't got bandwidth to review it but we will get to it 🙏

**Comment by owlas** [comment]
Hey @gpdenny we're just trying to set the priority for this (I'm closing it in the meantime until we prioritize it). Are you already operating this on a fork of Lightdash? Are you updating to the latest version?

**Comment by gpdenny** [comment]
@owlas 
We're simply not using the email features right now, so far I've not been asked to enable it, but I very much expect that to change in the future :sweat_smile:

**Pull request closed without merging**
