### PR TITLE
feat: upgrade blueprint to version 4

### PR DESCRIPTION
**Pull request by owlas**
⚠️ **Marking as blocked until we decide to upgrade. Just opening PR to share a preview with the team**

Following the [upgrade guide](https://github.com/palantir/blueprint/wiki/Blueprint-4.0):
* replaced all `bp3-` tags with `bp4-`
* Searched for any usages of deprecated apis, didn't find any

**Substantial changes** 

* Colours in the app are quite different, greys are much less blue. Primary action is brighter.
* Text fields have a strong contrasting bottom border
* Autocomplete fields have a more subtle active field design

### Pre requirements:
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: 

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by PriPatel** [comment]
Im torn @owlas !  The new blue really makes things pop. The only thing I'm not a huge fan of is the duller background but this is really subtle. I'd love to know what other people think!!

The only thing I found that looks a bit broken now is the navbar when it indicates which page you're on. It looks much better in our current version. 
Screenshot 2022-04-21 at 09 14 12

**Comment by ZeRego** [comment]
> Im torn @owlas ! The new blue really makes things pop. The only thing I'm not a huge fan of is the duller background but this is really subtle. I'd love to know what other people think!!
> 
> The only thing I found that looks a bit broken now is the navbar when it indicates which page you're on. It looks much better in our current version. Screenshot 2022-04-21 at 09 14 12

@PriPatel might be a 5 second fix to change the buttons in the nav bar from having intent `none` instead of `primary` which gives the blue tones.

**Comment by owlas** [comment]
I agree the nav-bar was my main concern too!

Otherwise I'm happy with it!

**Review by ZeRego — CHANGES_REQUESTED** [review]
lgtm :) 
We just need to fix the e2e tests since the selectors need to be changed to use `bp4-` instead of `bp3-`.

**Comment by nathaliabj** [comment]
Putting this back to draft, i realised the settings modal is pretty broken on this branch, would be good to have a proper QA around to see what else is broken, before merging this.
Screenshot 2022-04-22 at 12 17 07
Screenshot 2022-04-22 at 12 16 55

**Comment by owlas** [comment]
Whoa I didn't see this in my settings when trying this locally?!

**Comment by owlas** [comment]
Screenshot 2022-04-22 at 12 22 44

I can't replicate on the demo branch

**Comment by nathaliabj** [comment]
@owlas Woow! thats what i saw locally, maybe a bad build ? 
Lets merge this then 🥳

**Pull request merged**
