### PR TITLE
63 users can see the lineage of a model

### LINKED ISSUE #63: users can see the lineage of a model
When a user select a table, they can click on a `dependency graph` icon and see the upstream + downstream tables. 

image
image

(jamboard link: https://jamboard.google.com/d/1ecmP5iYwG5dKS5TL005-XVg5KAB9t8rYnHt_u6HzP18/viewer?f=0)

### PR DESCRIPTION
**Pull request by owlas**
Closes #63 

--
Also minor fix to docker file for #87 
Not sure this worked correctly for demo.lightdash.com - seems to be working for docs.lightdash.com

### CODE REVIEW

**Comment by owlas** [comment]
Closes #63

**Comment by owlas** [comment]
@hamzahc1 - added a lineage visualisation here: https://lightdash-pr-88.onrender.com/tables/orders?sidebar=base

Let me know what you think. 

The button is getting cut off, just fixing that

**Comment by hamzahc1** [comment]
A few notes:
1. When you hover on a node - the cursor changes to a pointer but there's no click functionality right now (I like the animation on hover, but I would remove the click pointer)
2.  Style-wise - Giving the other nodes a solid colour (with no border) would look cleaner 
3. Can we add a label or note that the lineage graph shows only one level upstream and downstream of the selected table if they exist? 
Otherwise, it looks good!

**Comment by owlas** [comment]
@hamzahc1 thanks! 

1. Fixing now 
2. I wanted to make it obvious which nodes are upstream vs downstream. But don't really wanna use 3 different colours, I think it would look a bit wild. What do you think? Do we need different colours? Referring to the spec in #63 
3. Would this be alright in documentation? Or maybe a small tooltip? I think having this permanently in the UI would be clutter

**Comment by hamzahc1** [comment]
@owlas 
2. I think you can use just two colours, one for central node (already exists) and then a second solid colour for all other nodes. This was mainly a style suggestion to look cleaner than having the black border.
3. Tooltip would work 👍

**Pull request merged**
