### PR TITLE
style: smaller scrollbar variant

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: #9406 

### Description:

Adds `primary` variant to `ScrollArea` component

Uses this new scroll component in: 
- ExploreTree sidebar
- Settings sidebar

Unfortunately, we can't add `defaultProps` to variants: https://github.com/orgs/mantinedev/discussions/5550

https://github.com/lightdash/lightdash/assets/7611706/a9825722-9703-48b7-8681-66b053bc7ca9

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by IrakliJani** [comment]
@joaoviana looks so cute, I love it!

two minor UI suggestions from me:
- It would be nice if we added fade-in and fade-out animations to the scrollbar.
- Also, if you hover over it and it darkens a bit (maybe transitioned?).

https://github.com/lightdash/lightdash/assets/962095/79b87b6c-dfb6-4756-9986-7e70aec07676

**Review by IrakliJani — APPROVED** [review]
looks good! minor comments

found one overflow bug which might or might not be related to this change:
https://github.com/lightdash/lightdash/assets/962095/08c6b72a-d918-4456-9c09-c1118ed5937e

**Comment by joaoviana** [comment]
> @joaoviana looks so cute, I love it!
> 
> two minor UI suggestions from me:
> 
> * It would be nice if we added fade-in and fade-out animations to the scrollbar.
> * Also, if you hover over it and it darkens a bit (maybe transitioned?).
> 
>  CleanShot.2024-03-21.at.19.37.13.mp4

ooooh, let me add these! Thinking 🤔

**Comment by joaoviana** [comment]
> looks good! minor comments
> 
> found one overflow bug which might or might not be related to this change: https://github.com/lightdash/lightdash/assets/962095/08c6b72a-d918-4456-9c09-c1118ed5937e


https://github.com/lightdash/lightdash/assets/7611706/1734559b-4515-4288-83f0-e6ef4c7f28c0

Just tested in `main` and same issue with the `Box` alternative :/ I believe it's to do with the `position:sticky` applied to the component that includes the _accordion_

**Comment by IrakliJani** [comment]
> Just tested in `main` and same issue with the `Box` alternative :/ I believe it's to do with the `position:sticky` applied to the component that includes the _accordion_

gotcha.. different issue

**Comment by joaoviana** [comment]
On here: https://github.com/lightdash/lightdash/pull/9479/commits/3c24d3f39760f2a64de68a82bd8620f671e42fb6

I've darkened the scrollbar on hover
I also added a `fadeIn` animation. 
Haven't worked out yet how to apply the `fadeOut` correctly, so didn't apply it. LMK what you think @IrakliJani & @PriPatel :)

**Pull request merged**
