### PR TITLE
feat: sort grouped series

### PR DESCRIPTION
**Pull request by rephus**
Closes: #3468
### Description:

[Screencast from 01-11-22 09:38:01.webm](https://user-images.githubusercontent.com/1983672/199193102-2f765e78-2e4f-44d0-9e1f-70f2dfdc27d4.webm)

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
I think something funky is happening when you start moving single series with any groups

https://www.loom.com/share/2244397ee1da4f9a8a9e87c262e4cf09

Here's the chart I was using: https://lightdash-pr-3626.onrender.com/share/0pNoEabqlhE1iZDZmJUlN

**Comment by rephus** [comment]
> I think something funky is happening when you start moving single series with many groups

Fixed :)

**Comment by ZeRego** [comment]
I noticed a problem ( that is also present in main ) where the series generated aren't ordered correctly. Opening a separate ticket to solve that. The series order can be fixed by changing the group order.
https://lightdash-pr-3626.onrender.com/share/zoLFGcnDBz8vIB6TV4pqB
Screenshot 2022-11-01 at 09 00 08

**Review by ZeRego — APPROVED** [review]
lgtm 👍

**Comment by TuringLovesDeathMetal** [comment]
Looks amazing! Thanks for fixing the weird grouping bug ❤️

**Pull request merged**
