### PR TITLE
feat: include raw time interval for timestamps

### PR DESCRIPTION
**Pull request by djayatillake**
Closes: #994 #1032 

### Description:
replaced millisecond with raw
changed convert dimension to only date_trunc if the time interval is not raw

### Preview:
I'm really struggling with environment so haven't seen this work or been able to run tests or lint!

### Scope of the changes (select all that apply):
- [ ] Backend

### CODE REVIEW

**Comment by djayatillake** [comment]
I chose not to use codespaces on Gravity's org and do it locally this time (so that the allow edits by maintainers tickbox is present in the PR), but really struggled to set up my environment locally... no idea what I'm doing.

Could I use codespaces in Lightdash org for future PRs?

**Comment by ZeRego** [comment]
> I chose not to use codespaces on Gravity's org and do it locally this time (so that the allow edits by maintainers tickbox is present in the PR), but really struggled to set up my environment locally... no idea what I'm doing.
> 
> Could I use codespaces in Lightdash org for future PRs?

Thanks for contributing 🎉 

Can you tell us what made it hard to set up the env locally ? Ideally in a new ticket so we can act upon it. 
I just created an issue to add a loom video in the docs so it's easier to follow our instructions. https://github.com/lightdash/lightdash/issues/1037

I don't think there is any problem if you use the codespaces for this PR and future ones. I have to be honest, I haven't used it that much to be aware of its cons. 

It seems like the indentation changed for the entire file, making it hard to see what are the real changes.
We have a pre-commit hook that should be linting and formatting the code in the commit. 🤔 

If you run the following commands do you see the files fixing the indentation to 4 spaces instead of 2 ? 
```shell
yarn lint
yarn format
```

**Comment by djayatillake** [comment]
David-Jayatillake:lightdash davidjayatillake$ yarn lint
yarn run v1.22.17
$ run-s common-lint backend-lint frontend-lint e2e-lint
/bin/sh: run-s: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by djayatillake** [comment]
David-Jayatillake:lightdash davidjayatillake$ yarn format
yarn run v1.22.17
$ run-s common-format backend-format frontend-format e2e-format
/bin/sh: run-s: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by djayatillake** [comment]
I'm not sure I understand enough of what is going wrong to make a ticket

**Comment by djayatillake** [comment]
I need to be added to your org to use codespaces here... not sure if it's ok for me to be added to your org?

**Comment by ZeRego** [comment]
> David-Jayatillake:lightdash davidjayatillake$ yarn format
> yarn run v1.22.17
> $ run-s common-format backend-format frontend-format e2e-format
> /bin/sh: run-s: command not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Ah got it, you need to have npm and yarn installed in your machine and then run `yarn install`. I'm going to record the loom videos to improve the docs and make a single bash script ( similar to the install script ). 

> I need to be added to your org to use codespaces here... not sure if it's ok for me to be added to your org?

That's something we need to evaluate and maybe create a role with limited permissions for regular contributors. 

> As a workaround, I've forked my fork to gravity org. Using codespaces there and then will PR to my fork and then those changes should merge into this PR once merged I think

👍  In the codespace you can run `yarn lint` and `yarn format` since it has all dependencies installed.

**Comment by djayatillake** [comment]
I had that same docker hub check fail last time, something to do with a login

**Comment by ZeRego** [comment]
e2e tests passing here: https://github.com/lightdash/lightdash/actions/runs/1601517356

**Pull request merged**
