### PR TITLE
feat: show resizable/movable charts in grid

### LINKED ISSUE #580: Dashboard UI: Dashboard page - charts display
- Display all selected charts on the page based on set up
- Add ability to drap & drop charts on the page 
- Add ability to resize chart

### PR DESCRIPTION
**Pull request by jaybe78**
This PR displays `<DashboardChartTile>` in a grid.
The layout of the grid is automatically saved on:
- `onDragStop`
- `onResizeStop`

Other changes:
- Made the height of the chart resizable
- Change grid item selection colour from red to grey 
- Change AddTileButton width to  300px

Closes #580

### CODE REVIEW

**Comment by jaybe78** [comment]
> I think we could have a sidebar, similar to the rest of of pages, to have the name and description and the 'add chart' button. What you think ? Not sure If this is the correct issue for this work/feedback.

I think a sidebar would be nice in the future but since we want to ship dashboard ASAP. 
May be for now we can just do what @hamzahc1 suggested which is to resize it a bit !?

**Comment by ZeRego** [comment]
> I think resizing the Add button and changing the red colour to a more neutral one when selecting an item should be easy.
I can do that as part of this ticket or in a new PR ? @ZeRego @owlas
The change is small so you can do it in this PR.

**Comment by TuringLovesDeathMetal** [comment]
> This can feel a bit odd - should all charts be at a fixed height so they "snap" to a fixed grid? 

mmm we could do that, but then you remove the ability to have charts that "stand out". E.g. if I had a chart of our "weekly active users over time", then I might have some smaller charts below it which are like "num new users over time", "% retention over time" --> these are kind of like "digging into" the weekly active users chart. But really, I'd want that to be bigger because it's the main metric we're concerned with.

It's not the end of hte world though if this isn't possible! If we can't change the height easily, then I'd fix the height :)

**Comment by owlas** [comment]
> Agree with @ZeRego that adding the sidebar for a continuous UX across the app is the right thing to do and will be the natural place for the other meta-information about the dashboard (including add chart button).

I'm less sure about this because the dashboard benefits hugely from having the full canvas, right now @jaybe78's design looks really clean and gives plenty of space for charts. We lose about 1/6th of the screen (minimum) by adding a sidebar, which is valuable screen space for charts.

Also agree that for v1 it's not so important.

What do you think @hamzahc1?

**Comment by jaybe78** [comment]
@TuringLovesDeathMetal @hamzahc1 @ZeRego @owlas 
I've added a quick fix for the height

https://user-images.githubusercontent.com/3605098/138078294-e0d51809-c8f1-4a2e-b758-f9a9dbba3e37.mov

What do you think about that ?

**Pull request merged**
