### PR TITLE
feat: search v2 UI

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/5254

### Description:

first version:
CleanShot 2024-02-16 at 20 39 59@2x

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by IrakliJani** [comment]
I need to fix `globalSearch` e2e

**Comment by almeidabbm** [comment]
Still reviewing the code, something I noticed.
Any chance we can fix this scroll bar clipping the border radius?

image

**Comment by almeidabbm** [comment]
> @almeidabbm oh, nice find! can't see that because its default hidden on mac. https://github.com/lightdash/lightdash/assets/962095/c5685b73-2755-4231-92a4-090f29ec9939

Could be be because of the browser? I am using chrome

**Comment by IrakliJani** [comment]
this does not seem like an easy fix but I'll keep trying. probably not in this PR tho

**Comment by almeidabbm** [comment]
> @almeidabbm its because of this setting on mac I think:
> 
> CleanShot 2024-02-21 at 20 50 17@2x

Gotcha! 🧐

**Review by almeidabbm — APPROVED** [review]
LGTM 🎉 

- After discussion with @IrakliJani we decided to take care of refactoring the whole sorting in a separate branch to make it easier to read

**Pull request merged**
