### PR TITLE
Fix: Special characters in table calculation column name

### PR DESCRIPTION
**Pull request by jaybe78**
Add function in common package to test whether column name has specials characters.
```
export const hasSpecialCharacters = (text: string) => /[^a-zA-Z ]/g.test(text);
```

Add toast error if
- special character is found
- column name already exists

### CODE REVIEW

**Review by owlas — APPROVED** [review]
Looks good. 

@ZeRego did you already have some logic in the form components to show inline validation errors? We could avoid the toast

**Comment by ZeRego** [comment]
> Looks good.
> 
> @ZeRego did you already have some logic in the form components to show inline validation errors? We could avoid the toast

Yes! :D 
We should now use [react form hooks ](https://react-hook-form.com/) + I wrote some wrappers with the blueprintjs components. 
You can see the wrapped components here :
https://github.com/lightdash/lightdash/tree/main/packages/frontend/src/components/ReactHookForm

Example of a form :

```
import Form from '../../ReactHookForm/Form';
import Input from '../../ReactHookForm/Input';

....
    const methods = useForm({
        defaultValues: {...},
    });
    
    const onSubmit = async (data) => { ... }

....

<Form methods={methods} onSubmit={onSubmit}>
            <Input
                name="example"
                label="Project"
                rules={{
                    required: 'Required field',
                    // add here your custom validation and error message
                }}
            />
            <Button
                type="submit"
                intent={Intent.PRIMARY}
                text="Save"
            />
</Form>
```

**Comment by jaybe78** [comment]
Closes: #472

**Comment by owlas** [comment]
lgtm!

**Comment by owlas** [comment]
For some reason the UI isn't deploying can't tell what's different about this branch. Did anyone manage to run e2e tests locally?

**Comment by ZeRego** [comment]
> For some reason the UI isn't deploying can't tell what's different about this branch. Did anyone manage to run e2e tests locally?

e2e tests failed because the pr env took more than 3 seconds to return result data. 

e2e tests passing here: https://github.com/lightdash/lightdash/actions/runs/1307845708

**Comment by owlas** [comment]
But I can't even see the preview env in render, can you?

**Comment by ZeRego** [comment]
> But I can't even see the preview env in render, can you?

I can see it. https://lightdash-pr-539.onrender.com/projects

**Comment by jaybe78** [comment]
> > Looks good.
> > @ZeRego did you already have some logic in the form components to show inline validation errors? We could avoid the toast
> 
> Yes! :D We should now use [react form hooks ](https://react-hook-form.com/) + I wrote some wrappers with the blueprintjs components. You can see the wrapped components here : https://github.com/lightdash/lightdash/tree/main/packages/frontend/src/components/ReactHookForm
> 
> Example of a form :
> 
> ```
> import Form from '../../ReactHookForm/Form';
> import Input from '../../ReactHookForm/Input';
> 
> ....
>     const methods = useForm({
>         defaultValues: {...},
>     });
>     
>     const onSubmit = async (data) => { ... }
> 
> ....
> 
> <Form methods={methods} onSubmit={onSubmit}>
>             <Input
>                 name="example"
>                 label="Project"
>                 rules={{
>                     required: 'Required field',
>                     // add here your custom validation and error message
>                 }}
>             />
>             <Button
>                 type="submit"
>                 intent={Intent.PRIMARY}
>                 text="Save"
>             />
> </Form>
> ```
> 
> This would mean refactoring the entire component so I won't request changes for this PR. I will leave up to you to decide if is worth to do it now or not.

Hi @ZeRego 
I've added a new wrapper for AceEditor and also now using Input component you developed to show error messages.
Cheers

**Pull request merged**
