### PR TITLE
Add chart settings space

### LINKED ISSUE #42: Add chart settings space
If you have more than one dimension + one measure in your table, you should be able to pick which things you want to have as the x, y and series.

image

image
image
image
image

### PR DESCRIPTION
**Pull request by owlas**
Closes #42

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
super cool to this coming to light!!!


Playing around with switching the x-axis, I was definitely expecting the grouping to change too. Not sure how easy this is to change? 🤔 I'll add it as a new issue to the backlog if it's a big thing!
https://www.loom.com/share/79e76567cc5a47dbb37e7cfeb54fe0b5

**Comment by owlas** [comment]
@TuringLovesDeathMetal yeah that's totally doable.

In this attempt I kept the state for the three options quite independent but they clearly are related to each other. I'll store them all together as one state, and when somebody changes the dimension or the groupBy etc. then we can cleanly fix the rest of the state. 

Hold tight!

**Comment by owlas** [comment]
I haven't styled this yet but had a thought:

There are rarely that many available dimensions and metrics in an active query. Perhaps Dropdowns aren't the best here. 

For metrics we could show them all and the user can toggle them on or off, that makes sense.

Less sure about the dimensions for the x-axis and groupBy. maybe just two simple buttons / radio buttons, that let you toggle which dimension is the x-axis and which is the group by

**Comment by owlas** [comment]
@TuringLovesDeathMetal check out the latest deployment.

This feels way more intuitive to me.
I ran with a different approach to the Dropdowns, I think this makes it much more visible how I'm controlling and modifying the plot layout.

I've also linked together all the different options, so you can't set unintuitive layouts (like same group and x dimension).

One thing I'm missing is a popover or something that makes it clear why you can't have: 
* Multiple metrics **and** a group by

**Comment by owlas** [comment]
Missing: 

- [ ] don't reset chart config if query results schema is unchanged (e.g. I only change sort and rerun)
- [ ] option to add two y-axes (possibly move to another ticket?)

**Comment by owlas** [comment]
Created sub tickets, sent #42

**Pull request merged**
