### PR TITLE
feat: table field list sort

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #3155 

### Description:
alphabet sort for tree node items

CleanShot 2022-09-06 at 12 22 30

### CODE REVIEW

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal should I also make group fields label regular font weight (instead of bold)?

**Comment by TuringLovesDeathMetal** [comment]
It feels like regular font weight might look nicer? 

@PriPatel Is there a reason why we chose bold here instead of regular font weight?

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal yes! because it felt clearer that those items 'contained' other items, but this wasnt tested or anything so I'm up for making it regular and seeing how we feel!

**Comment by IrakliJani** [comment]
IMO feels more natural this way @PriPatel @TuringLovesDeathMetal 
CleanShot 2022-09-06 at 12 59 03@2x

**Comment by PriPatel** [comment]
lets go for it :)

**Review by ZeRego — APPROVED** [review]
🥇

**Pull request merged**
