### PR TITLE
fix: filter autocomplete click bug

### PR DESCRIPTION
**Pull request by rephus**
Closes:  #3653

### Description:

[Screencast from 03-11-22 17:04:36.webm](https://user-images.githubusercontent.com/1983672/199773769-67052452-ca82-4bab-9f31-f2780b936771.webm)

### CODE REVIEW

**Review by IrakliJani — COMMENTED** [review]
@rephus if we remove the blur functionality we have to reopen this https://github.com/lightdash/lightdash/issues/3500

is there a chance to filter blur events if click fires from the autocomplete items?

if not - and this issue is a priority to ship please reopen the issue above, comment out the blur code and I will try to find a workaround.

**Comment by rephus** [comment]
> if Blur is present, it "prevents" any other interaction, 

Right, let me try that usecase

**Comment by rephus** [comment]
I'm fixing the previous discussed `on blur ` usecase, but only if the `input value` matches one of the options. But let me know if you think otherwise. /cc @ZeRego what do you think ? 


[Screencast from 04-11-22 15:25:10.webm](https://user-images.githubusercontent.com/1983672/199999461-1eab1083-6bbf-4500-b71c-0c218a1bed1e.webm)

**Comment by ZeRego** [comment]
> I'm fixing the previous discussed `on blur ` usecase, but only if the `input value` matches one of the options. But let me know if you think otherwise. /cc @ZeRego what do you think ?
> 
>  Screencast.from.04-11-22.15.25.10.webm

I like it 👍

**Review by ZeRego — APPROVED** [review]

**Comment by ZeRego** [comment]
The more I think about it the more I think it should set the value the user typed in ( not just if there is a perfect match )

**Comment by IrakliJani** [comment]
> The more I think about it the more I think it should set the value the user typed in ( not just if there is a perfect match )

@ZeRego Yeah... I think that's a better UX

**Pull request merged**
