### PR TITLE
feat: show or hide column calculation in table viz

### PR DESCRIPTION
**Pull request by ZeRego**
Closes: #2772 

### Description:

Note that all existing saved charts will have their footer hidden. 

show column calculation

### CODE REVIEW

**Review by TuringLovesDeathMetal — APPROVED** [review]
Niiiice! this looks great to me :) 

I feel like being able to toggle on/off totals in view mode would be amazing 😍 I'm going to open an issue for it and add it to the data interactivity milestone ✅

**Comment by rephus** [comment]
should it be `Show total row` or just `Show total`  ? I don't think it is a "column"

**Comment by ZeRego** [comment]
> should it be `Show total row` or just `Show total` ? I don't think it is a "column"

I came up with that label because we calculate all the values in the column. And I say 'calculate' since we are going to support further calculations beside totals (average, min, max, etc ) 
@TuringLovesDeathMetal thoughts ?

**Comment by rephus** [comment]
It looks like this ` show` property is not saved or not displayed correctly 

Peek 2022-08-08 14-02

This is causing another issue, I can't `save changes`

Peek 2022-08-08 14-00

**Comment by TuringLovesDeathMetal** [comment]
I'm not picky about `show total` vs. `show column total`! I think it's fine as-is. It's definitely not a row total :) 

Eventually we'll be adding `show row total` for pivot-tables. This will be where we sum everything in a row (e.g. all of row 6 summed).

**Comment by ZeRego** [comment]
@rephus thanks for testing ❤️  There was a typo after I renamed the variable that was causing the problems with saved charts 🙌

**Pull request merged**
