### PR TITLE
feat: proper sort indicators based on field type

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #3140 

### Description:
adds proper sort indicators based on field type

CleanShot 2022-09-05 at 20 07 02@2x
CleanShot 2022-09-05 at 20 07 15@2x
CleanShot 2022-09-05 at 20 07 21@2x
CleanShot 2022-09-05 at 20 07 27@2x

### CODE REVIEW

**Comment by IrakliJani** [comment]
@PriPatel does style updates look good to you? (see screenshots above)

**Comment by PriPatel** [comment]
@IrakliJani ...Nice! in the dropdown, I would increase the font-weight of the sort indicators
eg:
Sort **A-Z**

Id also increase the font weight of the item to filter so 
Filter by **This**

maybe this is a different problem and needs to go in another ticket. Apart from that though, looking good.

**Comment by IrakliJani** [comment]
@PriPatel 

CleanShot 2022-09-06 at 13 45 13@2x

---

@ZeRego I added new-old to date fields

CleanShot 2022-09-06 at 13 46 25@2x

I only use First-Last to boolean values now. any suggestions?

**Comment by PriPatel** [comment]
Agree with `old-new` and that we should get rid of `first-last.`

**Comment by IrakliJani** [comment]
@PriPatel @ZeRego for boolean should we just use `True-False` `False-True`

**Comment by PriPatel** [comment]
yeah, that makes most sense to me.

**Comment by IrakliJani** [comment]
https://user-images.githubusercontent.com/962095/188627631-387ee6f7-b66b-4e48-95e5-2de359b8c770.mp4

**Review by ZeRego — APPROVED** [review]

**Pull request merged**
