### PR TITLE
fix: support schema uppercase

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #2232

### Preview:
Screenshot from 2022-05-25 13-20-17

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [x] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by owlas** [comment]
I've just opened #2249, which alters this code. 



Why did this PR fix the problem?

**Comment by owlas** [comment]
I've just opened #2249, which alters this code. 



Why did this PR fix the problem?

**Comment by rephus** [comment]
> I've just opened #2249, which alters this code.
> 
> Why did this PR fix the problem?

on that PR I fixed the issue where the column is returned by the warehouse on lower_case but the schema.yml is on UPPERCASE. you can easily replicate this on postgress by changing one column on your schema.yml to UPPERCASE. I think that is the problem he had, but the description on the ticket doens't cover that. I don't think it is related with your PR (edited)

**Comment by rephus** [comment]
> I've just opened #2249, which alters this code.


Your code is a lot more generic as it is finding the item by ignoring its case, so this PR is no longer needed and should fix the issue

closing

**Pull request closed without merging**
