### PR TITLE
fix: remove unwanted footer text for unsupported

### PR DESCRIPTION
**Pull request by CVamsi27**
Closes: #5803 

### Description:
Updated onboarding screen for unsupported warehouse

### ScreenShorts:
image

### CODE REVIEW

**Comment by IrakliJani** [comment]
@CVamsi27 thanks for your contribution 🙌
you need to remove import of `InviteExpertFooter` otherwise build will not pass. you can test it locally before opening a PR by running `yarn load:env yarn build`

**Comment by CVamsi27** [comment]
@IrakliJani removed the import

**Review by IrakliJani — APPROVED** [review]
thanks @CVamsi27 all looks good!

**Comment by PriPatel** [comment]
Thanks both!!! <3

**Pull request merged**
