### PR TITLE
style: change save chart modal

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1487
### Description:
Add aditional paramenters to action modal, to update the chart, but not the dashboard 

### Preview:
Screenshot from 2022-04-05 15-35-40

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by owlas** [comment]
This looks great! 

Would it be a lot of effort to reproduce this with the base modal from the blueprint components: https://blueprintjs.com/docs/#core/components/alert

The `ActionModal` component is overly complex and @ZeRego and I had decided to try and phase this out

**Review by owlas — COMMENTED** [review]
This looks great!

Would it be a lot of effort to reproduce this with the base modal from the blueprint components: https://blueprintjs.com/docs/#core/components/alert

The ActionModal component is overly complex and @ZeRego and I had decided to try and phase this out

**Comment by rephus** [comment]
About Alerts: 
> Although similar to [dialogs](https://blueprintjs.com/docs/#core/components/dialog), alerts are more restrictive and should only be used for important information. By default, the user can only exit the alert by clicking one of the confirmation buttons—clicking the overlay or pressing the esc key will not close the alert. These interactions can be enabled via props.

Looks like I can't use Inputs inside this component, maybe we should try with Dialog instead...

This requires a bit of refactoring though, but I agree the whole `CreateSavedQueryModal` is a mess and very hacky

**Comment by owlas** [comment]
Oh my bad! I thought `Alert` could take anything in the container. I think a quick refactor with `Dialog` is worth it!

**Comment by rephus** [comment]
Updated to use simpler Dialog component (Alert comes with buttons, but without title, so the design doesn't match)

Screenshot from 2022-04-06 13-09-05

**Review by owlas — APPROVED** [review]
Beautiful - 🐑 it

**Comment by rephus** [comment]
> @rephus one change, this doesn't submit on hitting "enter" - I think the `Button` needs `type=submit`

Mmm, you're right. But adding type=submit to the button will not fix it (it is not even inside the `FormGroup` ... I could capture the ENTER key inside the onChange in the `InputGroup` and trigger the update method... what do you think ?

**Comment by owlas** [comment]
@rephus I think it should if you wrap a `<form>` tag around everything inside the dialog (buttons and form group)

**Comment by owlas** [comment]
Emphasis on _I THINK_

**Comment by rephus** [comment]
> Emphasis on _I THINK_

But the form is part of the BODY and the buttons are in the FOOTER >_< 

image

**Comment by owlas** [comment]
Like this:

```typescript
    return (
        <Dialog isOpen={isOpen} onClose={onClose} lazy title="Save chart">
            {' '}
            <form>
                <div className={Classes.DIALOG_BODY}>
                    <FormGroup
                        label="Enter a memorable name for your chart"
                        labelFor="chart-name"
                        style={{ fontWeight: 'bold' }}
                    >
                        <InputGroup
                            id="chart-name"
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="eg. How many weekly active users do we have?"
                        />
                    </FormGroup>
                </div>
                <div className={Classes.DIALOG_FOOTER}>
                    <div className={Classes.DIALOG_FOOTER_ACTIONS}>
                        <Button onClick={onClose}>Cancel</Button>
                        <Button
                            data-cy="submit-base-modal"
                            intent={Intent.SUCCESS}
                            text="Save"
                            onClick={() => {
                                mutate({ ...savedData, name });

                                if (onClose) onClose();
                            }}
                            disabled={isCreating || !name}
                        />
                    </div>
                </div>
            </form>
        </Dialog>
    );
```

**Comment by owlas** [comment]
Oh I've just tried this locally and it force refreshes the whole page and doesn't redirect properly, damn

**Comment by owlas** [comment]
Got it! 

```typescript
    return (
        <Dialog isOpen={isOpen} onClose={onClose} lazy title="Save chart">
            {' '}
            <form>
                <div className={Classes.DIALOG_BODY}>
                    <FormGroup
                        label="Enter a memorable name for your chart"
                        labelFor="chart-name"
                        style={{ fontWeight: 'bold' }}
                    >
                        <InputGroup
                            id="chart-name"
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="eg. How many weekly active users do we have?"
                        />
                    </FormGroup>
                </div>
                <div className={Classes.DIALOG_FOOTER}>
                    <div className={Classes.DIALOG_FOOTER_ACTIONS}>
                        <Button onClick={onClose}>Cancel</Button>
                        <Button
                            data-cy="submit-base-modal"
                            intent={Intent.SUCCESS}
                            text="Save"
                            type="submit"
                            onClick={(e) => {
                                mutate({ ...savedData, name });

                                if (onClose) onClose();
                                e.preventDefault();
                            }}
                            disabled={isCreating || !name}
                        />
                    </div>
                </div>
            </form>
        </Dialog>
```

**Comment by rephus** [comment]
@owlas tested your code and it works :smile: , so :ship:  it

**Pull request merged**
