### PR TITLE
feat: support metric filters for results table

### PR DESCRIPTION
**Pull request by rephus**
Closes: #3126 (part 2) 

### Description:

There might be some unsupported dimensions to filter. like when filtering a compiledSQL with another case on it, or dimensions from different tables. 

Screenshot from 2022-10-03 09-44-24

Screenshot from 2022-10-03 09-52-39

Screenshot from 2022-10-03 09-52-46

image

### CODE REVIEW

**Comment by rephus** [comment]
I'm happy to discuss different edge cases here

**Review by rephus — COMMENTED** [review]
@rephus remember to wrap conditions in (brackets) so we can do nested sql filtering

**Comment by rephus** [comment]
@ZeRego adding (Brackets) fixed the issue with nested SQL :ok_hand:

**Review by ZeRego — APPROVED** [review]
lgtm 👍

**Pull request merged**
