### PR TITLE
fix: clean up dashboard tiles

### PR DESCRIPTION
**Pull request by yasmin-e**
Closes:  #3696

### Description:
**In edit mode**

- Add hover state to dashboard tile (suggestion : drop shadow)
- Add selected state to dashboard tile (suggestion : blue border)
- Grab cursor when hovering over tile header
- Grabbing cursor when selecting tile to drag

**In view mode**

- The context menu and info icon should only show on hover.

### CODE REVIEW

**Comment by ZeRego** [comment]
Redeploying PR env since it failed with the latest commit.

**Comment by ZeRego** [comment]
When the title wraps into multiple lines, the buttons aren't displayed on the right. 
Screenshot 2022-12-16 at 09 52 39

**Comment by hamzahc1** [comment]
Not sure if this is intentional - but the dropdown under the 3-dot menu now appears on hover rather than on click? 
Screenshot 2022-12-16 at 13 44 56

**Comment by PriPatel** [comment]
@yasmin-e 
**Lets keep and ship the following changes:**
- Grab cursor when hovering over tile header
- Grabbing cursor when selecting tile to drag
- The new alignment of the info icon and the three-dots menu
- **In edit mode only :** The coloured outline of the tile when hovered and selected. The only change I'd make here is the animation. I would make it instant. 


**Let's leave the following changes out for now** whilst we try and overcome the technical challenges and come up with alt. suggestions:
- Showing the info icon and three-dot menu on hover (in both edit mode and view mode)
- The coloured outline of a tile when you hover over it in **view mode.**

**Comment by PriPatel** [comment]
> Is this intentional - the dropdown under the 3-dot menu now appears on hover rather than on click? Screenshot 2022-12-16 at 13 44 56

@hamzahc1 
Yes this was intentional due to limitations with Blueprint but we've decided that this isn't a good interaction because people **expect** to be able to click on the three dots. Right now, if you click on it, you dismiss it and this feels like a bug. This was the only way we could get the buttons to appear on hover and we've decided it is not a good change it and are exploring other options!

**Comment by hamzahc1** [comment]
Is there an update on this ticket @yasmin-e ?

**Comment by yasmin-e** [comment]
@hamzahc1 working on a very last fix, will probably merge before the end of the day

**Comment by PriPatel** [comment]
This is great! 🎉 I've tested against every item in my previous message and it has all been covered.  🎉 🎉 🎉

**Pull request merged**
