### PR TITLE
feat: value label options for sql runner charts

### PR DESCRIPTION
**Pull request by magnew**
Closes: #11924 

### Description:

Adds options for value labels in SQL runner charts. For now this is only enabled in chart with one series. Multiple series is blocked on fixing multi-series settings, the main ticket for which is: #11925 

Screenshot 2024-11-13 at 17 59 29

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by joaoviana — CHANGES_REQUESTED** [review]
when I set the value labels and save the chart, the saved chart doesn't contain the configuration

edit

image

saved (in view mode)

image

**Comment by magnew** [comment]
> when I set the value labels and save the chart, the saved chart doesn't contain the configuration
> 
> edit
> 
> image
> saved (in view mode)
> 
> image

The generated API was wrong. I ran it and I guess didn't notice. I've updated it, hopefully it works now.

**Review by joaoviana — APPROVED** [review]
works great 🙌

**Comment by magnew** [comment]
A failing test is open on every PR. Merging this.

**Pull request merged**
