### PR TITLE
fix: docker container name in contributing guide

### PR DESCRIPTION
**Pull request by 12ian34**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
n/a

### Description:
Minor typo in docker container name

### Preview:
image

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [x] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by owlas** [comment]
@all-contributors add @12ian34 for docs

**Comment by rephus** [comment]
On my machine is `lightdash-app_lightdash-dev_1` :thinking: 

image

**Comment by ZeRego** [comment]
iirc I got both name versions on MacOS. Should we have both in the docs or find a better command ? 🤔

**Comment by 12ian34** [comment]
This [SO post](https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore) seems relevant. We could consider adding `--compatibility` to the docker compose command so that it keeps the name consistent across devices and compose versions.

**Pull request merged**
