### PR TITLE
feat: update chart related buttons

### PR DESCRIPTION
**Pull request by joaoviana**
Closes: #7795

### Description:

Update saved chart headers in explore etc

https://github.com/lightdash/lightdash/assets/7611706/4467e213-3343-44f9-8450-0aa7560a3738

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by joaoviana** [comment]
I'm getting a not-so-good button style rendering when editing a chart from a dashboard:
* the button `Save changes` should be disabled by default when editing a chart from a dashboard on initial load; it goes green, then disabled.
Will check on Render if that's the case or just my local set up that has issues 😅

**Comment by ZeRego** [comment]
@joaoviana
Screenshot 2023-11-03 at 17 40 36

**Comment by joaoviana** [comment]
> @joaoviana isn't this the wrong green ? Screenshot 2023-11-03 at 17 40 36

should be darker? Need to find out the correct green.{some number}

**Comment by joaoviana** [comment]
> > @joaoviana isn't this the wrong green ? Screenshot 2023-11-03 at 17 40 36
> 
> should be darker? Need to find out the correct green.{some number}

changed to this: `green.7`

image

**Comment by IrakliJani** [comment]
@joaoviana should we just change it to blue? I don't know if we are using green buttons elsewhere

**Comment by joaoviana** [comment]
> @joaoviana should we just change it to blue? I don't know if we are using green buttons elsewhere

mantine buttons? No, I don't think so. Cool, can change it!

**Review by IrakliJani — APPROVED** [review]
looks great!

**Pull request merged**
