### PR TITLE
fix: cli onboarding code blocks

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #7577 

### Description:

❓ which one do you prefer?

CleanShot 2023-10-23 at 10 49 44@2x

CleanShot 2023-10-23 at 10 49 32@2x

I'm kinda leaning to dark theme but it pops too much

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by IrakliJani** [comment]
also updated this one

CleanShot 2023-10-23 at 11 20 28@2x

**Comment by owlas** [comment]
New one looks 100x better, great job @IrakliJani !

**Comment by owlas** [comment]
do we need to fix some e2e tests here?

**Comment by IrakliJani** [comment]
thanks @owlas

fyi, im keeping light mode for now

and rerunning tests, must be the flakiness

**Review by owlas — APPROVED** [review]

**Pull request merged**
