### PR TITLE
fix: bignumber text sizes and interactions

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #4455 
Related: #3174 
Closes: #4709 

### Description:

resizing:

https://user-images.githubusercontent.com/962095/223474480-023d107c-ee8f-4bc4-b580-04b18598d0be.mp4

---

title, action button interactions:

https://user-images.githubusercontent.com/962095/223763283-f8aab217-1ca6-4545-9ca3-b4edfd8fbad8.mp4

---

latest video in debug mode: (background is red for title wrapper for visibility what happens in the background)

https://user-images.githubusercontent.com/962095/223760757-85239cfe-3e58-43ff-b1e5-d78d9ebf30ed.mp4

### CODE REVIEW

**Review by yasmin-e — APPROVED** [review]
great work! 🚢

**Comment by PriPatel** [comment]
Looks great!! There is finally breathing space. 

Tiny nitpick that we've already discussed with #4709  is the slight animation when we show tile actions on hover - we should remove it for now for consistency.

**Comment by PriPatel** [comment]
Oops one last thing:
Can the hover target area for the chart title just be the chart title itself, rather than the whole span? Hard to explain but in the attached screenshot, my cursor was in the middle of the tile, right at the very top, and I was expecting the context menu to appear. 
Screenshot 2023-03-09 at 15 23 53

**Comment by IrakliJani** [comment]
@PriPatel fixed both issues!

**Pull request merged**
