### PR TITLE
fix: avoid requesting validation endpoint when no permission

### PR DESCRIPTION
**Pull request by anshul45**
Closes: (https://github.com/lightdash/lightdash/issues/9327)

### Description:
Fix the project validation details request if the user does not have permission to do so. I've figured out how it's validated on the Backend. Based on this. I've validate the user on the Frontend before making the validation request.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Comment by joaoviana** [comment]
Just changed the description of the PR @anshul45, reviewing this now, and running E2E tests 👍

**Comment by joaoviana** [comment]
Pushed 2 changes here @anshul45
1. Simplified the `useValidation` hook and renamed the boolean check variable to be clearer
2. Added `user` to the other place in the app where this hook is called. I recommend running the proper yarn commands to do the type checking. For example `yarn workspace frontend build` 👍 

Will merge once this passes E2E tests!

**Review by joaoviana — APPROVED** [review]

**Comment by joaoviana** [comment]
Thank you for contributing to Lightdash 🎉

**Comment by joaoviana** [comment]
@all-contributors add @anshul45 for code

**Comment by anshul45** [comment]
@joaoviana  Thank you for taking the time to review my pull request and optimize my code! I have learned a lot from this.

**Pull request merged**
