### PR TITLE
feat: sorting in the SQL runner

### PR DESCRIPTION
**Pull request by magnew**
Closes: #12427 

### Description:

Adds sorting on any column to the SQL runner.

Kapture 2024-11-15 at 16 14 57

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by TuringLovesDeathMetal — CHANGES_REQUESTED** [review]
change that we chatted about in slack - I don't think this should interact with the x-axis ordering (unlike the spec in the ticket)

**Comment by magnew** [comment]
> change that we chatted about in slack - I don't think this should interact with the x-axis ordering (unlike the spec in the ticket)

Removed sorting in the side bar

**Comment by magnew** [comment]
> > change that we chatted about in slack - I don't think this should interact with the x-axis ordering (unlike the spec in the ticket)
> 
> Removed sorting in the side bar

Added back after discussing more.

**Review by TuringLovesDeathMetal — APPROVED** [review]
nice! Looks great :)

**Review by joaoviana — APPROVED** [review]
Works great! 

Wondering if we should add a `light/subtle` ⬆️ ⬇️  button with a tooltip label `Sort`

(can be done on a separate PR btw!)

**Comment by magnew** [comment]
> Works great!
> 
> Wondering if we should add a `light/subtle` ⬆️ ⬇️ button with a tooltip label `Sort`
> 
> (can be done on a separate PR btw!)

We talked about it a little and left if off for now. I agree something would be nice though. Will follow up with something.

**Comment by magnew** [comment]
Failing test is failing in main. Im going to merge this.

**Pull request merged**
