### PR TITLE
feat: add dashboard header actions

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #2072

### Description:
adds dashboard header actions. see the video below:

https://user-images.githubusercontent.com/962095/184621563-1418dfaa-fee8-4529-855a-6a5192a7463c.mp4

### CODE REVIEW

**Comment by rephus** [comment]
Could we also add the `+ create new` space action ? If you think this is hard, we can do it on a separate ticket/pr 

image

**Comment by rephus** [comment]
Everything works perfectly :ok_hand:

**Comment by IrakliJani** [comment]
@rephus yup, will add that in the same PR

**Review by ZeRego — APPROVED** [review]
lgtm 🚀

**Pull request merged**
