### PR TITLE
feat: graphile migrate on migrations

### PR DESCRIPTION
**Pull request by rephus**
Closes: 

### Description:

I applied the migration on an existing schema, didn't fail 

Screenshot from 2023-02-09 15-19-56

### CODE REVIEW

**Comment by rephus** [comment]
Let's not merge this unless it keeps happening  https://lightdash.sentry.io/issues/3755257587/?project=5959292&referrer=issue_alert-slack

**Comment by owlas** [comment]
@rephus I think this is a great idea! This approach came to me in a dream last night 😂 - but it makes sense to run these as part of the knex migrations because then we can leverage the migration lock that knex uses 🙌 

Just to check - does this PR also disable auto-running migrations on worker start? I believe they also try to migrate on start by default

**Comment by rephus** [comment]
From their docs https://github.com/graphile/worker#library-usage-queueing-jobs

> NOTE: although running the worker will automatically install its schema, the same is not true for queuing jobs. You must ensure that the worker database schema is installed before you attempt to enqueue a job; you can install the database schema into your database with the following command:

I don't think we need to disable that initial schema installation

**Comment by owlas** [comment]
You're right @rephus ! They have an open feature request for this: https://github.com/graphile/worker/issues/143

Probably we can't avoid these errors appearing for the first migration. Let's close.

**Pull request closed without merging**
