### PR TITLE
fix: conditional formatting interactions

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: #4320 

### Description:

https://user-images.githubusercontent.com/962095/223071540-017bdae8-4047-45a3-824c-4da21eee8cf6.mp4

### CODE REVIEW

**Review by rephus — APPROVED** [review]
Nice. 

It doesn't work with black though... do we care ? 

[Screencast from 06-03-23 11:06:21.webm](https://user-images.githubusercontent.com/1983672/223079673-921611ea-0461-4f86-921d-45ee5bb13363.webm)

**Comment by IrakliJani** [comment]
@rephus yaaa, I have no idea what to do with blacks. any idea @PriPatel ?

**Comment by rephus** [comment]
I think we can merge this as it is. let's not overthink this black color, if we find a solution we can fix it on a separate PR

**Comment by IrakliJani** [comment]
@rephus agreed!

**Pull request merged**
