### PR TITLE
feat: select space on save chart

### PR DESCRIPTION
**Pull request by rephus**
Closes: #2667

### Description:

All existing SPACE features are behind a localstorage flag now, to enable just do `localStorage.setItem('spaceFeature', true) ` on console and refresh the page
Peek 2022-07-25 09-27

### CODE REVIEW

**Comment by TuringLovesDeathMetal** [comment]
hmmm, there's some weird stuff happening where there's like a "ghost" space 🤔 

https://www.loom.com/share/86bcc051ab3448c5b437d83c773f5c2a?from_recorder=1&focus_title=1

**Comment by rephus** [comment]
> hmmm, there's some weird stuff happening where there's like a "ghost" space thinking
> 
> https://www.loom.com/share/86bcc051ab3448c5b437d83c773f5c2a?from_recorder=1&focus_title=1

I think you posted the wrong loom recording :sweat_smile:

**Comment by TuringLovesDeathMetal** [comment]
🤦‍♀️ awe man. 

here it is! https://www.loom.com/share/ebbb8f358c9245af881dad2b17aaf692

Not sure if it's just because we haven't merged any of the visuals for the spaces stuff though? 🤔

**Comment by TuringLovesDeathMetal** [comment]
Missed teh comment in the PR about stuff being hidden!

Looks good to me :)

**Comment by rephus** [comment]
I added localstorage check to this new feature as well

**Review by ZeRego — APPROVED** [review]

**Pull request merged**
