### PR TITLE
fix: navigation menu styles

### PR DESCRIPTION
**Pull request by IrakliJani**
### Description:

fixes menu styles broken by this PR: https://github.com/lightdash/lightdash/pull/3095

CleanShot 2022-08-31 at 12 15 32

### CODE REVIEW

**Review by rephus — APPROVED** [review]
I tested it and it looks good. 

There is just one thing I found confusing,  when going into an individual chart, `all charts` is selected, same with dashboards

image

I confirmed this was also happening on the previous version, so no need to fix it here ,but we should probably create a separate issue. What do you think @PriPatel ?

**Comment by ZeRego** [comment]
@IrakliJani Since we migrated from MenuItem to MenuItem 2 we need to change the `NavLink.tsx` component to apply `active: true` instead of `selected: true` which is deprecated in MenuItem2.

**Comment by IrakliJani** [comment]
@ZeRego good call

@PriPatel

this is the default style with the `active` prop

CleanShot 2022-08-31 at 12 57 33@2x

compared to what we already have

CleanShot 2022-08-31 at 12 57 38@2x

**Comment by IrakliJani** [comment]
better screen with the active icon color
CleanShot 2022-08-31 at 13 05 13@2x

**Pull request merged**
