### PR TITLE
feat: remove delete space from space list

### PR DESCRIPTION
**Pull request by magnew**
Closes: #8666 

### Description:

Remove delete space action from spaces list. It made it too easy to permanently delete them. 
Screenshot 2024-01-19 at 18 02 03

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

**Review by joaoviana — APPROVED** [review]
Nice! Makes more sense to be able to delete it only on Space view 👍 

Tested on Render

**Review by PriPatel — COMMENTED** [review]
This could also apply to pinned dashboards and charts!

**Comment by magnew** [comment]
> This could also apply to pinned dashboards and charts!

Updated!

**Comment by PriPatel** [comment]
nice! works now. Fewer accidents shall take place :)

**Review by PriPatel — APPROVED** [review]

**Pull request merged**
