### PR TITLE
feat: when user has no charts or dashboards add existing button is hidden

### PR DESCRIPTION
**Pull request by yasmin-e**
Closes: #4479

### Description:
Screenshot 2023-02-16 at 11 14 14
Screenshot 2023-02-16 at 11 14 30

### CODE REVIEW

**Comment by PriPatel** [comment]
Yep, looks as expected! I think there are better changes we can make down the line such as not showing a submenu at all as there is now only one option. For now, hiding the invalid option is the obvious best step!
TY <3

**Review by owlas — CHANGES_REQUESTED** [review]
I can't quite figure out what the intended behaviour for margins should be but when there is only menu item, the vertical spacing is inconsistent

Screenshot 2023-02-16 at 14 54 53

**Comment by yasmin-e** [comment]
> I can't quite figure out what the intended behaviour for margins should be but when there is only menu item, the vertical spacing is inconsistent
> 
> Screenshot 2023-02-16 at 14 54 53

blueprint creates 2 menu wrappers around submenus instead of one giving it double margin than the normal items :disappointed: 
for that wonky margin, I know what I missed! thx

**Review by owlas — APPROVED** [review]
looks good!

**Pull request merged**
