### PR TITLE
feat: cell copy to clipboard

### PR DESCRIPTION
**Pull request by IrakliJani**
Closes: https://github.com/lightdash/lightdash/issues/3781

### Description:
add `mod+c` for table cells

⚠️ notice the animation

https://user-images.githubusercontent.com/962095/203594786-e23a909b-c564-4301-b60f-dafd8abc4a29.mp4

### CODE REVIEW

**Review by rephus — APPROVED** [review]
LGTM; also works in linux

**Review by rephus — CHANGES_REQUESTED** [review]
Ahh, there is an error on SQL runner, I get a blank page when I make a request (thanks E2E tests) Console doesn't return any useful error message.

**Comment by IrakliJani** [comment]
@rephus yeah 😂  I was thinking it was just another flaky test but then I checked locally and whole sql runner crashes. its because of the hotkey hook. im trying to refactor now

**Comment by rephus** [comment]
> @rephus yeah joy I was thinking it was just another flaky test but then I checked locally and whole sql runner crashes. its because of the hotkey hook. im trying to refactor now

Yeah, nice, I remember hotkey context used to wrap most of the app before, and that was causing a lot of unnecessary renders. So Jose changed it somehow. make sure the new version doesn't cause any regression :pray:

**Review by rephus — APPROVED** [review]
Looks good, everything is working now

**Pull request merged**
