### PR TITLE
feat: update default chart configs

### PR DESCRIPTION
**Pull request by rephus**
### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1607

### Description:
Update default chart configs, based on this https://www.notion.so/lightdash/Default-chart-configurations-5d3001af990d4b6fa990dba4564540f6

### Preview:
// one metric , one dimension

image

 // two metrics, one dimension
image

// 2 metrics, no dimensions

image

// 2 dimensions, no metrics

image

// >=2 metrics >=2 dimensions
image

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

### CODE REVIEW

**Comment by rephus** [comment]
@owlas @nathaliabj first, let me know if this is the right place to implement the default. If so, could you help me with this pivotKey ? I can't get it working . I've tried using `setPivotDimensions` hook, and also updating the `pivotKey` variable in this component..

**Comment by owlas** [comment]
@rephus are you using the `getItemId` function? I just found this other usage here: https://github.com/lightdash/lightdash/blob/50ce39a5aa28cc1c9fdf98aea2d6a9521a8921b3/packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx#L129-L137

**Comment by rephus** [comment]
> @rephus are you using the `getItemId` function? I just found this other usage here:
> 
> https://github.com/lightdash/lightdash/blob/50ce39a5aa28cc1c9fdf98aea2d6a9521a8921b3/packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx#L129-L137

I was debugging that usage, I think getItem id returns the same dimension id I'm using , but I'll check again

**Review by TuringLovesDeathMetal — COMMENTED** [review]
@rephus Any chance that we could change the default chart type for metric vs. metric to be a scatterplot instead of a column chart?

So, this scenario: 
> // 2 metrics, no dimensions

**Comment by rephus** [comment]
> @rephus Any chance that we could change the default chart type for metric vs. metric to be a scatterplot instead of a column chart?
> 
> So, this scenario:
> 
> > // 2 metrics, no dimensions

Done 

image

**Review by TuringLovesDeathMetal — APPROVED** [review]
niiiiice! looks good to me :)

**Review by owlas — CHANGES_REQUESTED** [review]
Using the PR preview and starting from an empty explore I get really different results, is the latest code pushed?

### 1 metric 1 dimension

Screenshot 2022-04-06 at 10 50 32

If I select 1 metric + 1 dimension it plots them the wrong way around

### 1 metric 2 dimensions
Screenshot 2022-04-06 at 10 52 28

If I select 1 metric and 2 two dimensions it groups by the same dimension as on the axis

### 2 metrics 1 dimension

Screenshot 2022-04-06 at 10 55 03

It only plots one metric

**Comment by rephus** [comment]
thanks @owlas for the testing

1metric + 1 dimension 

You were right, my axes were reverted. 

image

1 metric + 2 dimensions (pivot) 
that looks good to me :/

Peek 2022-04-06 13-44
 
2 metrics + 1 dimension 

This also looks ok

image

I think sometimes the chart doesn't refresh, maybe because the chart config is saved in a `state` (maybe just by opening the chart config)  so it doesn't take the default ? Try refreshing the page, you should see the right chart...

**Comment by TuringLovesDeathMetal** [comment]
@rephus for the second chart - I'd expect the `date` field to be the x-axis by default (always). 

If there are multiple date fields, then we can just pick the one further left in the results table to be the x-axis and teh other to be the group. 

But if there's one date field, and one non-date field in hte dimensions, I'd expect the date field to always be put on the x-axis by default. 

Sorry, I feel like I keep adding new requirements here 🙃

**Comment by TuringLovesDeathMetal** [comment]
@rephus I've just opened a new ticket for the dates stuff - so we can do it as a separate piece of work :)

So, ignore my comment above!

**Comment by owlas** [comment]
@rephus this has some conflicts!

**Comment by owlas** [comment]
Hey @rephus you're right about the chart refreshing. 

I think we have some refactoring to do with the charts to make them behave like we'd expect. I'm going to merge this as it is!

**Pull request merged**
