### PR TITLE
Fill Missing date gaps when viewing charts.

### LINKED ISSUE #357: If you've selected a date column on the x-axis and the date values in your table aren't gapless, we should fill in the gaps
I'm not actually sure whether or not we should do this...but I thought I'd stick it in so we could chat about it. 

Basically, if I have a table of data where the x-axis is built from a date dimension, but the dates in my table aren't gapless, then it produces a deceiving chart:

image

It gives you the values that you have in the table (unsurprisingly), but what this means is you have a time series plot with a bunch of holes in it that are "invisible". 
I feel like if you have a date column, you want the x-axis to be a line of gapless dates: so you can see where there are NULL values and then you can see where there are actual values. 

One way of potentially doing this is by plotting the full date values, then anything that's empty is set to `null`. Then, in the chart options, you can pick `set null values to...` so that you can have 0 values instead of the `null` on your plot.

### PR DESCRIPTION
**Pull request by silentninja**
Add filling missing gaps feature to CHANGELOG.md

Fixes #357

### CODE REVIEW

**Comment by silentninja** [comment]
https://www.loom.com/share/58ad06cef6d34a12920ee2bf15297608

**Comment by silentninja** [comment]
This PR fills the missing gaps for the date series. I have been using it for a very specific purpose and it is quite limited. Would love feedback to make it complete.

Limitations:
1. Cannot be used with group dimensions
2. Limited to days(can be extended to fill other time series)
3. Days column has to be sorted 
4. Default values cannot be customized for now
5. Using filters does not disable the option to fill gaps and ends up with a wrong result and should be prevented.

**Comment by ZeRego** [comment]
> Would love feedback to make it complete.
@silentninja left a couple in the issue ticket about some of the limitations you mentioned and a different approach.

**Comment by owlas** [comment]
This has been fixed in #755

**Pull request closed without merging**
