### PR TITLE
fix: exclude hidden tables and fields from global search

### PR DESCRIPTION
**Pull request by ZeRego**
Closes: #3637

### Description:

Example with `orders` hidden metric and table configuration only has `orders` visible.
```
      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null
        meta:
          dimension:
            hidden: true
```

global search

### CODE REVIEW

**Review by rephus — COMMENTED** [review]
I'm not sure what you're trying to do here. Do'nt we have already a `hidden` attribute on fields and tables ?

**Comment by ZeRego** [comment]
> I'm not sure what you're trying to do here. Do'nt we have already a `hidden` attribute on fields and tables ?

@rephus global search results currently display tables and fields that are marked as hidden, My changes exclude them from the search results

**Comment by rephus** [comment]
Code looks good, after filtering out the tables, I can't find them on global search, however I can still see the fields from disabled tables..

All tables
Screenshot from 2022-11-04 11-02-47


Disable stg_ tables: 
Screenshot from 2022-11-04 11-02-37

Screenshot from 2022-11-04 11-03-31

**Comment by ZeRego** [comment]
> Code looks good, after filtering out the tables, I can't find them on global search, however I can still see the fields from disabled tables..
> 
> All tables Screenshot from 2022-11-04 11-02-47
> 
> Disable stg_ tables: Screenshot from 2022-11-04 11-02-37
> 
> Screenshot from 2022-11-04 11-03-31

@rephus We cache the search results in the FE. So if you searched for 'status' before applying the table selection it will still show in the results. If you refresh the page after applying the table selection and then search, it won't show the field from the hidden table.

**Review by rephus — APPROVED** [review]

**Pull request merged**
